// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagegeneration"
)

// ImageGenerationCreate is the builder for creating a ImageGeneration entity.
type ImageGenerationCreate struct {
	config
	mutation *ImageGenerationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *ImageGenerationCreate) SetUserID(v int64) *ImageGenerationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *ImageGenerationCreate) SetConversationID(v int64) *ImageGenerationCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetParentGenerationID sets the "parent_generation_id" field.
func (_c *ImageGenerationCreate) SetParentGenerationID(v int64) *ImageGenerationCreate {
	_c.mutation.SetParentGenerationID(v)
	return _c
}

// SetNillableParentGenerationID sets the "parent_generation_id" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableParentGenerationID(v *int64) *ImageGenerationCreate {
	if v != nil {
		_c.SetParentGenerationID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ImageGenerationCreate) SetProvider(v string) *ImageGenerationCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableProvider(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetProviderCredentialID sets the "provider_credential_id" field.
func (_c *ImageGenerationCreate) SetProviderCredentialID(v int64) *ImageGenerationCreate {
	_c.mutation.SetProviderCredentialID(v)
	return _c
}

// SetNillableProviderCredentialID sets the "provider_credential_id" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableProviderCredentialID(v *int64) *ImageGenerationCreate {
	if v != nil {
		_c.SetProviderCredentialID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *ImageGenerationCreate) SetModel(v string) *ImageGenerationCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableModel(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetGenerationType sets the "generation_type" field.
func (_c *ImageGenerationCreate) SetGenerationType(v imagegeneration.GenerationType) *ImageGenerationCreate {
	_c.mutation.SetGenerationType(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *ImageGenerationCreate) SetPrompt(v string) *ImageGenerationCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *ImageGenerationCreate) SetSize(v string) *ImageGenerationCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableSize(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetRatio sets the "ratio" field.
func (_c *ImageGenerationCreate) SetRatio(v string) *ImageGenerationCreate {
	_c.mutation.SetRatio(v)
	return _c
}

// SetNillableRatio sets the "ratio" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableRatio(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetRatio(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ImageGenerationCreate) SetStatus(v imagegeneration.Status) *ImageGenerationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableStatus(v *imagegeneration.Status) *ImageGenerationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *ImageGenerationCreate) SetIdempotencyKey(v string) *ImageGenerationCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableIdempotencyKey(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetProviderRequestID sets the "provider_request_id" field.
func (_c *ImageGenerationCreate) SetProviderRequestID(v string) *ImageGenerationCreate {
	_c.mutation.SetProviderRequestID(v)
	return _c
}

// SetNillableProviderRequestID sets the "provider_request_id" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableProviderRequestID(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetProviderRequestID(*v)
	}
	return _c
}

// SetProviderOriginalURL sets the "provider_original_url" field.
func (_c *ImageGenerationCreate) SetProviderOriginalURL(v string) *ImageGenerationCreate {
	_c.mutation.SetProviderOriginalURL(v)
	return _c
}

// SetNillableProviderOriginalURL sets the "provider_original_url" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableProviderOriginalURL(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetProviderOriginalURL(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *ImageGenerationCreate) SetErrorCode(v string) *ImageGenerationCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableErrorCode(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ImageGenerationCreate) SetErrorMessage(v string) *ImageGenerationCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableErrorMessage(v *string) *ImageGenerationCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *ImageGenerationCreate) SetDurationMs(v int) *ImageGenerationCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableDurationMs(v *int) *ImageGenerationCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ImageGenerationCreate) SetStartedAt(v time.Time) *ImageGenerationCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableStartedAt(v *time.Time) *ImageGenerationCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ImageGenerationCreate) SetCompletedAt(v time.Time) *ImageGenerationCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableCompletedAt(v *time.Time) *ImageGenerationCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageGenerationCreate) SetCreatedAt(v time.Time) *ImageGenerationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableCreatedAt(v *time.Time) *ImageGenerationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImageGenerationCreate) SetUpdatedAt(v time.Time) *ImageGenerationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ImageGenerationCreate) SetNillableUpdatedAt(v *time.Time) *ImageGenerationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ImageGenerationMutation object of the builder.
func (_c *ImageGenerationCreate) Mutation() *ImageGenerationMutation {
	return _c.mutation
}

// Save creates the ImageGeneration in the database.
func (_c *ImageGenerationCreate) Save(ctx context.Context) (*ImageGeneration, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageGenerationCreate) SaveX(ctx context.Context) *ImageGeneration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageGenerationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageGenerationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageGenerationCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := imagegeneration.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := imagegeneration.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := imagegeneration.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.Ratio(); !ok {
		v := imagegeneration.DefaultRatio
		_c.mutation.SetRatio(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := imagegeneration.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := imagegeneration.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imagegeneration.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := imagegeneration.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageGenerationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImageGeneration.user_id"`)}
	}
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "ImageGeneration.conversation_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ImageGeneration.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := imagegeneration.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ImageGeneration.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := imagegeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GenerationType(); !ok {
		return &ValidationError{Name: "generation_type", err: errors.New(`ent: missing required field "ImageGeneration.generation_type"`)}
	}
	if v, ok := _c.mutation.GenerationType(); ok {
		if err := imagegeneration.GenerationTypeValidator(v); err != nil {
			return &ValidationError{Name: "generation_type", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.generation_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "ImageGeneration.prompt"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "ImageGeneration.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := imagegeneration.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ratio(); !ok {
		return &ValidationError{Name: "ratio", err: errors.New(`ent: missing required field "ImageGeneration.ratio"`)}
	}
	if v, ok := _c.mutation.Ratio(); ok {
		if err := imagegeneration.RatioValidator(v); err != nil {
			return &ValidationError{Name: "ratio", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.ratio": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ImageGeneration.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := imagegeneration.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := imagegeneration.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderRequestID(); ok {
		if err := imagegeneration.ProviderRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_request_id", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider_request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderOriginalURL(); ok {
		if err := imagegeneration.ProviderOriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "provider_original_url", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider_original_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := imagegeneration.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "ImageGeneration.duration_ms"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageGeneration.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImageGeneration.updated_at"`)}
	}
	return nil
}

func (_c *ImageGenerationCreate) sqlSave(ctx context.Context) (*ImageGeneration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageGenerationCreate) createSpec() (*ImageGeneration, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageGeneration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imagegeneration.Table, sqlgraph.NewFieldSpec(imagegeneration.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(imagegeneration.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(imagegeneration.FieldConversationID, field.TypeInt64, value)
		_node.ConversationID = value
	}
	if value, ok := _c.mutation.ParentGenerationID(); ok {
		_spec.SetField(imagegeneration.FieldParentGenerationID, field.TypeInt64, value)
		_node.ParentGenerationID = &value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(imagegeneration.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderCredentialID(); ok {
		_spec.SetField(imagegeneration.FieldProviderCredentialID, field.TypeInt64, value)
		_node.ProviderCredentialID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(imagegeneration.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.GenerationType(); ok {
		_spec.SetField(imagegeneration.FieldGenerationType, field.TypeEnum, value)
		_node.GenerationType = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(imagegeneration.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(imagegeneration.FieldSize, field.TypeString, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Ratio(); ok {
		_spec.SetField(imagegeneration.FieldRatio, field.TypeString, value)
		_node.Ratio = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(imagegeneration.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(imagegeneration.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.ProviderRequestID(); ok {
		_spec.SetField(imagegeneration.FieldProviderRequestID, field.TypeString, value)
		_node.ProviderRequestID = &value
	}
	if value, ok := _c.mutation.ProviderOriginalURL(); ok {
		_spec.SetField(imagegeneration.FieldProviderOriginalURL, field.TypeString, value)
		_node.ProviderOriginalURL = &value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(imagegeneration.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(imagegeneration.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(imagegeneration.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(imagegeneration.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(imagegeneration.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imagegeneration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imagegeneration.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageGeneration.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageGenerationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageGenerationCreate) OnConflict(opts ...sql.ConflictOption) *ImageGenerationUpsertOne {
	_c.conflict = opts
	return &ImageGenerationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageGenerationCreate) OnConflictColumns(columns ...string) *ImageGenerationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageGenerationUpsertOne{
		create: _c,
	}
}

type (
	// ImageGenerationUpsertOne is the builder for "upsert"-ing
	//  one ImageGeneration node.
	ImageGenerationUpsertOne struct {
		create *ImageGenerationCreate
	}

	// ImageGenerationUpsert is the "OnConflict" setter.
	ImageGenerationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *ImageGenerationUpsert) SetUserID(v int64) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateUserID() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ImageGenerationUpsert) AddUserID(v int64) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldUserID, v)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ImageGenerationUpsert) SetConversationID(v int64) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateConversationID() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldConversationID)
	return u
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ImageGenerationUpsert) AddConversationID(v int64) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldConversationID, v)
	return u
}

// SetParentGenerationID sets the "parent_generation_id" field.
func (u *ImageGenerationUpsert) SetParentGenerationID(v int64) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldParentGenerationID, v)
	return u
}

// UpdateParentGenerationID sets the "parent_generation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateParentGenerationID() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldParentGenerationID)
	return u
}

// AddParentGenerationID adds v to the "parent_generation_id" field.
func (u *ImageGenerationUpsert) AddParentGenerationID(v int64) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldParentGenerationID, v)
	return u
}

// ClearParentGenerationID clears the value of the "parent_generation_id" field.
func (u *ImageGenerationUpsert) ClearParentGenerationID() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldParentGenerationID)
	return u
}

// SetProvider sets the "provider" field.
func (u *ImageGenerationUpsert) SetProvider(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateProvider() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldProvider)
	return u
}

// SetProviderCredentialID sets the "provider_credential_id" field.
func (u *ImageGenerationUpsert) SetProviderCredentialID(v int64) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldProviderCredentialID, v)
	return u
}

// UpdateProviderCredentialID sets the "provider_credential_id" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateProviderCredentialID() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldProviderCredentialID)
	return u
}

// AddProviderCredentialID adds v to the "provider_credential_id" field.
func (u *ImageGenerationUpsert) AddProviderCredentialID(v int64) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldProviderCredentialID, v)
	return u
}

// ClearProviderCredentialID clears the value of the "provider_credential_id" field.
func (u *ImageGenerationUpsert) ClearProviderCredentialID() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldProviderCredentialID)
	return u
}

// SetModel sets the "model" field.
func (u *ImageGenerationUpsert) SetModel(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateModel() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldModel)
	return u
}

// SetGenerationType sets the "generation_type" field.
func (u *ImageGenerationUpsert) SetGenerationType(v imagegeneration.GenerationType) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldGenerationType, v)
	return u
}

// UpdateGenerationType sets the "generation_type" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateGenerationType() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldGenerationType)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *ImageGenerationUpsert) SetPrompt(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdatePrompt() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldPrompt)
	return u
}

// SetSize sets the "size" field.
func (u *ImageGenerationUpsert) SetSize(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateSize() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldSize)
	return u
}

// SetRatio sets the "ratio" field.
func (u *ImageGenerationUpsert) SetRatio(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldRatio, v)
	return u
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateRatio() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldRatio)
	return u
}

// SetStatus sets the "status" field.
func (u *ImageGenerationUpsert) SetStatus(v imagegeneration.Status) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateStatus() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldStatus)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ImageGenerationUpsert) SetIdempotencyKey(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateIdempotencyKey() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ImageGenerationUpsert) ClearIdempotencyKey() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldIdempotencyKey)
	return u
}

// SetProviderRequestID sets the "provider_request_id" field.
func (u *ImageGenerationUpsert) SetProviderRequestID(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldProviderRequestID, v)
	return u
}

// UpdateProviderRequestID sets the "provider_request_id" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateProviderRequestID() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldProviderRequestID)
	return u
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (u *ImageGenerationUpsert) ClearProviderRequestID() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldProviderRequestID)
	return u
}

// SetProviderOriginalURL sets the "provider_original_url" field.
func (u *ImageGenerationUpsert) SetProviderOriginalURL(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldProviderOriginalURL, v)
	return u
}

// UpdateProviderOriginalURL sets the "provider_original_url" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateProviderOriginalURL() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldProviderOriginalURL)
	return u
}

// ClearProviderOriginalURL clears the value of the "provider_original_url" field.
func (u *ImageGenerationUpsert) ClearProviderOriginalURL() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldProviderOriginalURL)
	return u
}

// SetErrorCode sets the "error_code" field.
func (u *ImageGenerationUpsert) SetErrorCode(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldErrorCode, v)
	return u
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateErrorCode() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldErrorCode)
	return u
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageGenerationUpsert) ClearErrorCode() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldErrorCode)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ImageGenerationUpsert) SetErrorMessage(v string) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateErrorMessage() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ImageGenerationUpsert) ClearErrorMessage() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldErrorMessage)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *ImageGenerationUpsert) SetDurationMs(v int) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateDurationMs() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *ImageGenerationUpsert) AddDurationMs(v int) *ImageGenerationUpsert {
	u.Add(imagegeneration.FieldDurationMs, v)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *ImageGenerationUpsert) SetStartedAt(v time.Time) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateStartedAt() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ImageGenerationUpsert) ClearStartedAt() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *ImageGenerationUpsert) SetCompletedAt(v time.Time) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateCompletedAt() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ImageGenerationUpsert) ClearCompletedAt() *ImageGenerationUpsert {
	u.SetNull(imagegeneration.FieldCompletedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageGenerationUpsert) SetUpdatedAt(v time.Time) *ImageGenerationUpsert {
	u.Set(imagegeneration.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageGenerationUpsert) UpdateUpdatedAt() *ImageGenerationUpsert {
	u.SetExcluded(imagegeneration.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageGenerationUpsertOne) UpdateNewValues() *ImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imagegeneration.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageGenerationUpsertOne) Ignore() *ImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageGenerationUpsertOne) DoNothing() *ImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageGenerationCreate.OnConflict
// documentation for more info.
func (u *ImageGenerationUpsertOne) Update(set func(*ImageGenerationUpsert)) *ImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageGenerationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImageGenerationUpsertOne) SetUserID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImageGenerationUpsertOne) AddUserID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateUserID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateUserID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ImageGenerationUpsertOne) SetConversationID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ImageGenerationUpsertOne) AddConversationID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateConversationID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateConversationID()
	})
}

// SetParentGenerationID sets the "parent_generation_id" field.
func (u *ImageGenerationUpsertOne) SetParentGenerationID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetParentGenerationID(v)
	})
}

// AddParentGenerationID adds v to the "parent_generation_id" field.
func (u *ImageGenerationUpsertOne) AddParentGenerationID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddParentGenerationID(v)
	})
}

// UpdateParentGenerationID sets the "parent_generation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateParentGenerationID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateParentGenerationID()
	})
}

// ClearParentGenerationID clears the value of the "parent_generation_id" field.
func (u *ImageGenerationUpsertOne) ClearParentGenerationID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearParentGenerationID()
	})
}

// SetProvider sets the "provider" field.
func (u *ImageGenerationUpsertOne) SetProvider(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateProvider() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateProvider()
	})
}

// SetProviderCredentialID sets the "provider_credential_id" field.
func (u *ImageGenerationUpsertOne) SetProviderCredentialID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetProviderCredentialID(v)
	})
}

// AddProviderCredentialID adds v to the "provider_credential_id" field.
func (u *ImageGenerationUpsertOne) AddProviderCredentialID(v int64) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddProviderCredentialID(v)
	})
}

// UpdateProviderCredentialID sets the "provider_credential_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateProviderCredentialID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateProviderCredentialID()
	})
}

// ClearProviderCredentialID clears the value of the "provider_credential_id" field.
func (u *ImageGenerationUpsertOne) ClearProviderCredentialID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearProviderCredentialID()
	})
}

// SetModel sets the "model" field.
func (u *ImageGenerationUpsertOne) SetModel(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateModel() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateModel()
	})
}

// SetGenerationType sets the "generation_type" field.
func (u *ImageGenerationUpsertOne) SetGenerationType(v imagegeneration.GenerationType) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetGenerationType(v)
	})
}

// UpdateGenerationType sets the "generation_type" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateGenerationType() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateGenerationType()
	})
}

// SetPrompt sets the "prompt" field.
func (u *ImageGenerationUpsertOne) SetPrompt(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdatePrompt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdatePrompt()
	})
}

// SetSize sets the "size" field.
func (u *ImageGenerationUpsertOne) SetSize(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateSize() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateSize()
	})
}

// SetRatio sets the "ratio" field.
func (u *ImageGenerationUpsertOne) SetRatio(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetRatio(v)
	})
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateRatio() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateRatio()
	})
}

// SetStatus sets the "status" field.
func (u *ImageGenerationUpsertOne) SetStatus(v imagegeneration.Status) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateStatus() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateStatus()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ImageGenerationUpsertOne) SetIdempotencyKey(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateIdempotencyKey() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ImageGenerationUpsertOne) ClearIdempotencyKey() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetProviderRequestID sets the "provider_request_id" field.
func (u *ImageGenerationUpsertOne) SetProviderRequestID(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetProviderRequestID(v)
	})
}

// UpdateProviderRequestID sets the "provider_request_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateProviderRequestID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateProviderRequestID()
	})
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (u *ImageGenerationUpsertOne) ClearProviderRequestID() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearProviderRequestID()
	})
}

// SetProviderOriginalURL sets the "provider_original_url" field.
func (u *ImageGenerationUpsertOne) SetProviderOriginalURL(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetProviderOriginalURL(v)
	})
}

// UpdateProviderOriginalURL sets the "provider_original_url" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateProviderOriginalURL() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateProviderOriginalURL()
	})
}

// ClearProviderOriginalURL clears the value of the "provider_original_url" field.
func (u *ImageGenerationUpsertOne) ClearProviderOriginalURL() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearProviderOriginalURL()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *ImageGenerationUpsertOne) SetErrorCode(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateErrorCode() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageGenerationUpsertOne) ClearErrorCode() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ImageGenerationUpsertOne) SetErrorMessage(v string) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateErrorMessage() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ImageGenerationUpsertOne) ClearErrorMessage() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearErrorMessage()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *ImageGenerationUpsertOne) SetDurationMs(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *ImageGenerationUpsertOne) AddDurationMs(v int) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateDurationMs() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateDurationMs()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ImageGenerationUpsertOne) SetStartedAt(v time.Time) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateStartedAt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ImageGenerationUpsertOne) ClearStartedAt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ImageGenerationUpsertOne) SetCompletedAt(v time.Time) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateCompletedAt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ImageGenerationUpsertOne) ClearCompletedAt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageGenerationUpsertOne) SetUpdatedAt(v time.Time) *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertOne) UpdateUpdatedAt() *ImageGenerationUpsertOne {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ImageGenerationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageGenerationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageGenerationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageGenerationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageGenerationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageGenerationCreateBulk is the builder for creating many ImageGeneration entities in bulk.
type ImageGenerationCreateBulk struct {
	config
	err      error
	builders []*ImageGenerationCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageGeneration entities in the database.
func (_c *ImageGenerationCreateBulk) Save(ctx context.Context) ([]*ImageGeneration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageGeneration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageGenerationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageGenerationCreateBulk) SaveX(ctx context.Context) []*ImageGeneration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageGenerationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageGenerationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageGeneration.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageGenerationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageGenerationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageGenerationUpsertBulk {
	_c.conflict = opts
	return &ImageGenerationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageGenerationCreateBulk) OnConflictColumns(columns ...string) *ImageGenerationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageGenerationUpsertBulk{
		create: _c,
	}
}

// ImageGenerationUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageGeneration nodes.
type ImageGenerationUpsertBulk struct {
	create *ImageGenerationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageGenerationUpsertBulk) UpdateNewValues() *ImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imagegeneration.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageGeneration.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageGenerationUpsertBulk) Ignore() *ImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageGenerationUpsertBulk) DoNothing() *ImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageGenerationCreateBulk.OnConflict
// documentation for more info.
func (u *ImageGenerationUpsertBulk) Update(set func(*ImageGenerationUpsert)) *ImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageGenerationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImageGenerationUpsertBulk) SetUserID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImageGenerationUpsertBulk) AddUserID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateUserID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateUserID()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ImageGenerationUpsertBulk) SetConversationID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetConversationID(v)
	})
}

// AddConversationID adds v to the "conversation_id" field.
func (u *ImageGenerationUpsertBulk) AddConversationID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateConversationID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateConversationID()
	})
}

// SetParentGenerationID sets the "parent_generation_id" field.
func (u *ImageGenerationUpsertBulk) SetParentGenerationID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetParentGenerationID(v)
	})
}

// AddParentGenerationID adds v to the "parent_generation_id" field.
func (u *ImageGenerationUpsertBulk) AddParentGenerationID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddParentGenerationID(v)
	})
}

// UpdateParentGenerationID sets the "parent_generation_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateParentGenerationID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateParentGenerationID()
	})
}

// ClearParentGenerationID clears the value of the "parent_generation_id" field.
func (u *ImageGenerationUpsertBulk) ClearParentGenerationID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearParentGenerationID()
	})
}

// SetProvider sets the "provider" field.
func (u *ImageGenerationUpsertBulk) SetProvider(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateProvider() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateProvider()
	})
}

// SetProviderCredentialID sets the "provider_credential_id" field.
func (u *ImageGenerationUpsertBulk) SetProviderCredentialID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetProviderCredentialID(v)
	})
}

// AddProviderCredentialID adds v to the "provider_credential_id" field.
func (u *ImageGenerationUpsertBulk) AddProviderCredentialID(v int64) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddProviderCredentialID(v)
	})
}

// UpdateProviderCredentialID sets the "provider_credential_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateProviderCredentialID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateProviderCredentialID()
	})
}

// ClearProviderCredentialID clears the value of the "provider_credential_id" field.
func (u *ImageGenerationUpsertBulk) ClearProviderCredentialID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearProviderCredentialID()
	})
}

// SetModel sets the "model" field.
func (u *ImageGenerationUpsertBulk) SetModel(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateModel() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateModel()
	})
}

// SetGenerationType sets the "generation_type" field.
func (u *ImageGenerationUpsertBulk) SetGenerationType(v imagegeneration.GenerationType) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetGenerationType(v)
	})
}

// UpdateGenerationType sets the "generation_type" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateGenerationType() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateGenerationType()
	})
}

// SetPrompt sets the "prompt" field.
func (u *ImageGenerationUpsertBulk) SetPrompt(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdatePrompt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdatePrompt()
	})
}

// SetSize sets the "size" field.
func (u *ImageGenerationUpsertBulk) SetSize(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateSize() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateSize()
	})
}

// SetRatio sets the "ratio" field.
func (u *ImageGenerationUpsertBulk) SetRatio(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetRatio(v)
	})
}

// UpdateRatio sets the "ratio" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateRatio() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateRatio()
	})
}

// SetStatus sets the "status" field.
func (u *ImageGenerationUpsertBulk) SetStatus(v imagegeneration.Status) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateStatus() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateStatus()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *ImageGenerationUpsertBulk) SetIdempotencyKey(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateIdempotencyKey() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *ImageGenerationUpsertBulk) ClearIdempotencyKey() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetProviderRequestID sets the "provider_request_id" field.
func (u *ImageGenerationUpsertBulk) SetProviderRequestID(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetProviderRequestID(v)
	})
}

// UpdateProviderRequestID sets the "provider_request_id" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateProviderRequestID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateProviderRequestID()
	})
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (u *ImageGenerationUpsertBulk) ClearProviderRequestID() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearProviderRequestID()
	})
}

// SetProviderOriginalURL sets the "provider_original_url" field.
func (u *ImageGenerationUpsertBulk) SetProviderOriginalURL(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetProviderOriginalURL(v)
	})
}

// UpdateProviderOriginalURL sets the "provider_original_url" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateProviderOriginalURL() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateProviderOriginalURL()
	})
}

// ClearProviderOriginalURL clears the value of the "provider_original_url" field.
func (u *ImageGenerationUpsertBulk) ClearProviderOriginalURL() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearProviderOriginalURL()
	})
}

// SetErrorCode sets the "error_code" field.
func (u *ImageGenerationUpsertBulk) SetErrorCode(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetErrorCode(v)
	})
}

// UpdateErrorCode sets the "error_code" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateErrorCode() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateErrorCode()
	})
}

// ClearErrorCode clears the value of the "error_code" field.
func (u *ImageGenerationUpsertBulk) ClearErrorCode() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearErrorCode()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ImageGenerationUpsertBulk) SetErrorMessage(v string) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateErrorMessage() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *ImageGenerationUpsertBulk) ClearErrorMessage() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearErrorMessage()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *ImageGenerationUpsertBulk) SetDurationMs(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *ImageGenerationUpsertBulk) AddDurationMs(v int) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateDurationMs() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateDurationMs()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ImageGenerationUpsertBulk) SetStartedAt(v time.Time) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateStartedAt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ImageGenerationUpsertBulk) ClearStartedAt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ImageGenerationUpsertBulk) SetCompletedAt(v time.Time) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateCompletedAt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ImageGenerationUpsertBulk) ClearCompletedAt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.ClearCompletedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageGenerationUpsertBulk) SetUpdatedAt(v time.Time) *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageGenerationUpsertBulk) UpdateUpdatedAt() *ImageGenerationUpsertBulk {
	return u.Update(func(s *ImageGenerationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ImageGenerationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageGenerationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageGenerationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageGenerationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
