// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imageprovidercredential"
)

// ImageProviderCredential is the model entity for the ImageProviderCredential schema.
type ImageProviderCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider imageprovidercredential.Provider `json:"provider,omitempty"`
	// AES-256-GCM encrypted upstream API key
	APIKeyEncrypted string `json:"-"`
	// Masked fingerprint, e.g. last 4 chars, for backend identification only
	KeyFingerprint string `json:"key_fingerprint,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Lower value = higher priority
	Priority int `json:"priority,omitempty"`
	// Weight for weighted round robin
	Weight int `json:"weight,omitempty"`
	// Status holds the value of the "status" field.
	Status imageprovidercredential.Status `json:"status,omitempty"`
	// ConsecutiveFailures holds the value of the "consecutive_failures" field.
	ConsecutiveFailures int `json:"consecutive_failures,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// LastSuccessAt holds the value of the "last_success_at" field.
	LastSuccessAt *time.Time `json:"last_success_at,omitempty"`
	// LastFailureAt holds the value of the "last_failure_at" field.
	LastFailureAt *time.Time `json:"last_failure_at,omitempty"`
	// CooldownUntil holds the value of the "cooldown_until" field.
	CooldownUntil *time.Time `json:"cooldown_until,omitempty"`
	// LastErrorCode holds the value of the "last_error_code" field.
	LastErrorCode *string `json:"last_error_code,omitempty"`
	// LastErrorMessage holds the value of the "last_error_message" field.
	LastErrorMessage *string `json:"last_error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageProviderCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imageprovidercredential.FieldEnabled:
			values[i] = new(sql.NullBool)
		case imageprovidercredential.FieldID, imageprovidercredential.FieldPriority, imageprovidercredential.FieldWeight, imageprovidercredential.FieldConsecutiveFailures:
			values[i] = new(sql.NullInt64)
		case imageprovidercredential.FieldName, imageprovidercredential.FieldProvider, imageprovidercredential.FieldAPIKeyEncrypted, imageprovidercredential.FieldKeyFingerprint, imageprovidercredential.FieldStatus, imageprovidercredential.FieldLastErrorCode, imageprovidercredential.FieldLastErrorMessage:
			values[i] = new(sql.NullString)
		case imageprovidercredential.FieldLastUsedAt, imageprovidercredential.FieldLastSuccessAt, imageprovidercredential.FieldLastFailureAt, imageprovidercredential.FieldCooldownUntil, imageprovidercredential.FieldCreatedAt, imageprovidercredential.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageProviderCredential fields.
func (_m *ImageProviderCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imageprovidercredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imageprovidercredential.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case imageprovidercredential.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = imageprovidercredential.Provider(value.String)
			}
		case imageprovidercredential.FieldAPIKeyEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_encrypted", values[i])
			} else if value.Valid {
				_m.APIKeyEncrypted = value.String
			}
		case imageprovidercredential.FieldKeyFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_fingerprint", values[i])
			} else if value.Valid {
				_m.KeyFingerprint = value.String
			}
		case imageprovidercredential.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case imageprovidercredential.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case imageprovidercredential.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case imageprovidercredential.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = imageprovidercredential.Status(value.String)
			}
		case imageprovidercredential.FieldConsecutiveFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_failures", values[i])
			} else if value.Valid {
				_m.ConsecutiveFailures = int(value.Int64)
			}
		case imageprovidercredential.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		case imageprovidercredential.FieldLastSuccessAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_success_at", values[i])
			} else if value.Valid {
				_m.LastSuccessAt = new(time.Time)
				*_m.LastSuccessAt = value.Time
			}
		case imageprovidercredential.FieldLastFailureAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_failure_at", values[i])
			} else if value.Valid {
				_m.LastFailureAt = new(time.Time)
				*_m.LastFailureAt = value.Time
			}
		case imageprovidercredential.FieldCooldownUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_until", values[i])
			} else if value.Valid {
				_m.CooldownUntil = new(time.Time)
				*_m.CooldownUntil = value.Time
			}
		case imageprovidercredential.FieldLastErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_code", values[i])
			} else if value.Valid {
				_m.LastErrorCode = new(string)
				*_m.LastErrorCode = value.String
			}
		case imageprovidercredential.FieldLastErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_message", values[i])
			} else if value.Valid {
				_m.LastErrorMessage = new(string)
				*_m.LastErrorMessage = value.String
			}
		case imageprovidercredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imageprovidercredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageProviderCredential.
// This includes values selected through modifiers, order, etc.
func (_m *ImageProviderCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImageProviderCredential.
// Note that you need to call ImageProviderCredential.Unwrap() before calling this method if this ImageProviderCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageProviderCredential) Update() *ImageProviderCredentialUpdateOne {
	return NewImageProviderCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageProviderCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageProviderCredential) Unwrap() *ImageProviderCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageProviderCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageProviderCredential) String() string {
	var builder strings.Builder
	builder.WriteString("ImageProviderCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provider))
	builder.WriteString(", ")
	builder.WriteString("api_key_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("key_fingerprint=")
	builder.WriteString(_m.KeyFingerprint)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("consecutive_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveFailures))
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastSuccessAt; v != nil {
		builder.WriteString("last_success_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastFailureAt; v != nil {
		builder.WriteString("last_failure_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CooldownUntil; v != nil {
		builder.WriteString("cooldown_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastErrorCode; v != nil {
		builder.WriteString("last_error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastErrorMessage; v != nil {
		builder.WriteString("last_error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ImageProviderCredentials is a parsable slice of ImageProviderCredential.
type ImageProviderCredentials []*ImageProviderCredential
