// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageprovidercredential"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageProviderCredentialUpdate is the builder for updating ImageProviderCredential entities.
type ImageProviderCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *ImageProviderCredentialMutation
}

// Where appends a list predicates to the ImageProviderCredentialUpdate builder.
func (_u *ImageProviderCredentialUpdate) Where(ps ...predicate.ImageProviderCredential) *ImageProviderCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ImageProviderCredentialUpdate) SetName(v string) *ImageProviderCredentialUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableName(v *string) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ImageProviderCredentialUpdate) SetProvider(v imageprovidercredential.Provider) *ImageProviderCredentialUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableProvider(v *imageprovidercredential.Provider) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_u *ImageProviderCredentialUpdate) SetAPIKeyEncrypted(v string) *ImageProviderCredentialUpdate {
	_u.mutation.SetAPIKeyEncrypted(v)
	return _u
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableAPIKeyEncrypted(v *string) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetAPIKeyEncrypted(*v)
	}
	return _u
}

// SetKeyFingerprint sets the "key_fingerprint" field.
func (_u *ImageProviderCredentialUpdate) SetKeyFingerprint(v string) *ImageProviderCredentialUpdate {
	_u.mutation.SetKeyFingerprint(v)
	return _u
}

// SetNillableKeyFingerprint sets the "key_fingerprint" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableKeyFingerprint(v *string) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetKeyFingerprint(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ImageProviderCredentialUpdate) SetEnabled(v bool) *ImageProviderCredentialUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableEnabled(v *bool) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ImageProviderCredentialUpdate) SetPriority(v int) *ImageProviderCredentialUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillablePriority(v *int) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ImageProviderCredentialUpdate) AddPriority(v int) *ImageProviderCredentialUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ImageProviderCredentialUpdate) SetWeight(v int) *ImageProviderCredentialUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableWeight(v *int) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ImageProviderCredentialUpdate) AddWeight(v int) *ImageProviderCredentialUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageProviderCredentialUpdate) SetStatus(v imageprovidercredential.Status) *ImageProviderCredentialUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableStatus(v *imageprovidercredential.Status) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *ImageProviderCredentialUpdate) SetConsecutiveFailures(v int) *ImageProviderCredentialUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableConsecutiveFailures(v *int) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *ImageProviderCredentialUpdate) AddConsecutiveFailures(v int) *ImageProviderCredentialUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ImageProviderCredentialUpdate) SetLastUsedAt(v time.Time) *ImageProviderCredentialUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableLastUsedAt(v *time.Time) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ImageProviderCredentialUpdate) ClearLastUsedAt() *ImageProviderCredentialUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_u *ImageProviderCredentialUpdate) SetLastSuccessAt(v time.Time) *ImageProviderCredentialUpdate {
	_u.mutation.SetLastSuccessAt(v)
	return _u
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableLastSuccessAt(v *time.Time) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetLastSuccessAt(*v)
	}
	return _u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (_u *ImageProviderCredentialUpdate) ClearLastSuccessAt() *ImageProviderCredentialUpdate {
	_u.mutation.ClearLastSuccessAt()
	return _u
}

// SetLastFailureAt sets the "last_failure_at" field.
func (_u *ImageProviderCredentialUpdate) SetLastFailureAt(v time.Time) *ImageProviderCredentialUpdate {
	_u.mutation.SetLastFailureAt(v)
	return _u
}

// SetNillableLastFailureAt sets the "last_failure_at" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableLastFailureAt(v *time.Time) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetLastFailureAt(*v)
	}
	return _u
}

// ClearLastFailureAt clears the value of the "last_failure_at" field.
func (_u *ImageProviderCredentialUpdate) ClearLastFailureAt() *ImageProviderCredentialUpdate {
	_u.mutation.ClearLastFailureAt()
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *ImageProviderCredentialUpdate) SetCooldownUntil(v time.Time) *ImageProviderCredentialUpdate {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableCooldownUntil(v *time.Time) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *ImageProviderCredentialUpdate) ClearCooldownUntil() *ImageProviderCredentialUpdate {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *ImageProviderCredentialUpdate) SetLastErrorCode(v string) *ImageProviderCredentialUpdate {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableLastErrorCode(v *string) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *ImageProviderCredentialUpdate) ClearLastErrorCode() *ImageProviderCredentialUpdate {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *ImageProviderCredentialUpdate) SetLastErrorMessage(v string) *ImageProviderCredentialUpdate {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdate) SetNillableLastErrorMessage(v *string) *ImageProviderCredentialUpdate {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *ImageProviderCredentialUpdate) ClearLastErrorMessage() *ImageProviderCredentialUpdate {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageProviderCredentialUpdate) SetUpdatedAt(v time.Time) *ImageProviderCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ImageProviderCredentialMutation object of the builder.
func (_u *ImageProviderCredentialUpdate) Mutation() *ImageProviderCredentialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageProviderCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageProviderCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageProviderCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageProviderCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageProviderCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imageprovidercredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageProviderCredentialUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := imageprovidercredential.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := imageprovidercredential.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyEncrypted(); ok {
		if err := imageprovidercredential.APIKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "api_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.api_key_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyFingerprint(); ok {
		if err := imageprovidercredential.KeyFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "key_fingerprint", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.key_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Weight(); ok {
		if err := imageprovidercredential.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imageprovidercredential.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := imageprovidercredential.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.last_error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageProviderCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageprovidercredential.Table, imageprovidercredential.Columns, sqlgraph.NewFieldSpec(imageprovidercredential.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(imageprovidercredential.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(imageprovidercredential.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(imageprovidercredential.FieldAPIKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyFingerprint(); ok {
		_spec.SetField(imageprovidercredential.FieldKeyFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(imageprovidercredential.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(imageprovidercredential.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(imageprovidercredential.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(imageprovidercredential.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(imageprovidercredential.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imageprovidercredential.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(imageprovidercredential.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(imageprovidercredential.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(imageprovidercredential.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSuccessAt(); ok {
		_spec.SetField(imageprovidercredential.FieldLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessAtCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastFailureAt(); ok {
		_spec.SetField(imageprovidercredential.FieldLastFailureAt, field.TypeTime, value)
	}
	if _u.mutation.LastFailureAtCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastFailureAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(imageprovidercredential.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(imageprovidercredential.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(imageprovidercredential.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(imageprovidercredential.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageprovidercredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageprovidercredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageProviderCredentialUpdateOne is the builder for updating a single ImageProviderCredential entity.
type ImageProviderCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageProviderCredentialMutation
}

// SetName sets the "name" field.
func (_u *ImageProviderCredentialUpdateOne) SetName(v string) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableName(v *string) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ImageProviderCredentialUpdateOne) SetProvider(v imageprovidercredential.Provider) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableProvider(v *imageprovidercredential.Provider) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetAPIKeyEncrypted sets the "api_key_encrypted" field.
func (_u *ImageProviderCredentialUpdateOne) SetAPIKeyEncrypted(v string) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetAPIKeyEncrypted(v)
	return _u
}

// SetNillableAPIKeyEncrypted sets the "api_key_encrypted" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableAPIKeyEncrypted(v *string) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetAPIKeyEncrypted(*v)
	}
	return _u
}

// SetKeyFingerprint sets the "key_fingerprint" field.
func (_u *ImageProviderCredentialUpdateOne) SetKeyFingerprint(v string) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetKeyFingerprint(v)
	return _u
}

// SetNillableKeyFingerprint sets the "key_fingerprint" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableKeyFingerprint(v *string) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetKeyFingerprint(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ImageProviderCredentialUpdateOne) SetEnabled(v bool) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableEnabled(v *bool) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ImageProviderCredentialUpdateOne) SetPriority(v int) *ImageProviderCredentialUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillablePriority(v *int) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ImageProviderCredentialUpdateOne) AddPriority(v int) *ImageProviderCredentialUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ImageProviderCredentialUpdateOne) SetWeight(v int) *ImageProviderCredentialUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableWeight(v *int) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ImageProviderCredentialUpdateOne) AddWeight(v int) *ImageProviderCredentialUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageProviderCredentialUpdateOne) SetStatus(v imageprovidercredential.Status) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableStatus(v *imageprovidercredential.Status) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *ImageProviderCredentialUpdateOne) SetConsecutiveFailures(v int) *ImageProviderCredentialUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableConsecutiveFailures(v *int) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *ImageProviderCredentialUpdateOne) AddConsecutiveFailures(v int) *ImageProviderCredentialUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *ImageProviderCredentialUpdateOne) SetLastUsedAt(v time.Time) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableLastUsedAt(v *time.Time) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *ImageProviderCredentialUpdateOne) ClearLastUsedAt() *ImageProviderCredentialUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_u *ImageProviderCredentialUpdateOne) SetLastSuccessAt(v time.Time) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetLastSuccessAt(v)
	return _u
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableLastSuccessAt(v *time.Time) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetLastSuccessAt(*v)
	}
	return _u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (_u *ImageProviderCredentialUpdateOne) ClearLastSuccessAt() *ImageProviderCredentialUpdateOne {
	_u.mutation.ClearLastSuccessAt()
	return _u
}

// SetLastFailureAt sets the "last_failure_at" field.
func (_u *ImageProviderCredentialUpdateOne) SetLastFailureAt(v time.Time) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetLastFailureAt(v)
	return _u
}

// SetNillableLastFailureAt sets the "last_failure_at" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableLastFailureAt(v *time.Time) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetLastFailureAt(*v)
	}
	return _u
}

// ClearLastFailureAt clears the value of the "last_failure_at" field.
func (_u *ImageProviderCredentialUpdateOne) ClearLastFailureAt() *ImageProviderCredentialUpdateOne {
	_u.mutation.ClearLastFailureAt()
	return _u
}

// SetCooldownUntil sets the "cooldown_until" field.
func (_u *ImageProviderCredentialUpdateOne) SetCooldownUntil(v time.Time) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetCooldownUntil(v)
	return _u
}

// SetNillableCooldownUntil sets the "cooldown_until" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableCooldownUntil(v *time.Time) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetCooldownUntil(*v)
	}
	return _u
}

// ClearCooldownUntil clears the value of the "cooldown_until" field.
func (_u *ImageProviderCredentialUpdateOne) ClearCooldownUntil() *ImageProviderCredentialUpdateOne {
	_u.mutation.ClearCooldownUntil()
	return _u
}

// SetLastErrorCode sets the "last_error_code" field.
func (_u *ImageProviderCredentialUpdateOne) SetLastErrorCode(v string) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetLastErrorCode(v)
	return _u
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableLastErrorCode(v *string) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetLastErrorCode(*v)
	}
	return _u
}

// ClearLastErrorCode clears the value of the "last_error_code" field.
func (_u *ImageProviderCredentialUpdateOne) ClearLastErrorCode() *ImageProviderCredentialUpdateOne {
	_u.mutation.ClearLastErrorCode()
	return _u
}

// SetLastErrorMessage sets the "last_error_message" field.
func (_u *ImageProviderCredentialUpdateOne) SetLastErrorMessage(v string) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetLastErrorMessage(v)
	return _u
}

// SetNillableLastErrorMessage sets the "last_error_message" field if the given value is not nil.
func (_u *ImageProviderCredentialUpdateOne) SetNillableLastErrorMessage(v *string) *ImageProviderCredentialUpdateOne {
	if v != nil {
		_u.SetLastErrorMessage(*v)
	}
	return _u
}

// ClearLastErrorMessage clears the value of the "last_error_message" field.
func (_u *ImageProviderCredentialUpdateOne) ClearLastErrorMessage() *ImageProviderCredentialUpdateOne {
	_u.mutation.ClearLastErrorMessage()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageProviderCredentialUpdateOne) SetUpdatedAt(v time.Time) *ImageProviderCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ImageProviderCredentialMutation object of the builder.
func (_u *ImageProviderCredentialUpdateOne) Mutation() *ImageProviderCredentialMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageProviderCredentialUpdate builder.
func (_u *ImageProviderCredentialUpdateOne) Where(ps ...predicate.ImageProviderCredential) *ImageProviderCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageProviderCredentialUpdateOne) Select(field string, fields ...string) *ImageProviderCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageProviderCredential entity.
func (_u *ImageProviderCredentialUpdateOne) Save(ctx context.Context) (*ImageProviderCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageProviderCredentialUpdateOne) SaveX(ctx context.Context) *ImageProviderCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageProviderCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageProviderCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageProviderCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imageprovidercredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageProviderCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := imageprovidercredential.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := imageprovidercredential.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyEncrypted(); ok {
		if err := imageprovidercredential.APIKeyEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "api_key_encrypted", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.api_key_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyFingerprint(); ok {
		if err := imageprovidercredential.KeyFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "key_fingerprint", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.key_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Weight(); ok {
		if err := imageprovidercredential.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imageprovidercredential.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorCode(); ok {
		if err := imageprovidercredential.LastErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_error_code", err: fmt.Errorf(`ent: validator failed for field "ImageProviderCredential.last_error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageProviderCredentialUpdateOne) sqlSave(ctx context.Context) (_node *ImageProviderCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageprovidercredential.Table, imageprovidercredential.Columns, sqlgraph.NewFieldSpec(imageprovidercredential.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageProviderCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imageprovidercredential.FieldID)
		for _, f := range fields {
			if !imageprovidercredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imageprovidercredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(imageprovidercredential.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(imageprovidercredential.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.APIKeyEncrypted(); ok {
		_spec.SetField(imageprovidercredential.FieldAPIKeyEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyFingerprint(); ok {
		_spec.SetField(imageprovidercredential.FieldKeyFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(imageprovidercredential.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(imageprovidercredential.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(imageprovidercredential.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(imageprovidercredential.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(imageprovidercredential.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imageprovidercredential.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(imageprovidercredential.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(imageprovidercredential.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(imageprovidercredential.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSuccessAt(); ok {
		_spec.SetField(imageprovidercredential.FieldLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.LastSuccessAtCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastFailureAt(); ok {
		_spec.SetField(imageprovidercredential.FieldLastFailureAt, field.TypeTime, value)
	}
	if _u.mutation.LastFailureAtCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastFailureAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CooldownUntil(); ok {
		_spec.SetField(imageprovidercredential.FieldCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.CooldownUntilCleared() {
		_spec.ClearField(imageprovidercredential.FieldCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastErrorCode(); ok {
		_spec.SetField(imageprovidercredential.FieldLastErrorCode, field.TypeString, value)
	}
	if _u.mutation.LastErrorCodeCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastErrorMessage(); ok {
		_spec.SetField(imageprovidercredential.FieldLastErrorMessage, field.TypeString, value)
	}
	if _u.mutation.LastErrorMessageCleared() {
		_spec.ClearField(imageprovidercredential.FieldLastErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageprovidercredential.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ImageProviderCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageprovidercredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
