// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageasset"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageAssetUpdate is the builder for updating ImageAsset entities.
type ImageAssetUpdate struct {
	config
	hooks    []Hook
	mutation *ImageAssetMutation
}

// Where appends a list predicates to the ImageAssetUpdate builder.
func (_u *ImageAssetUpdate) Where(ps ...predicate.ImageAsset) *ImageAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageAssetUpdate) SetUpdatedAt(v time.Time) *ImageAssetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ImageAssetUpdate) SetDeletedAt(v time.Time) *ImageAssetUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableDeletedAt(v *time.Time) *ImageAssetUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ImageAssetUpdate) ClearDeletedAt() *ImageAssetUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageAssetUpdate) SetUserID(v int64) *ImageAssetUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableUserID(v *int64) *ImageAssetUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImageAssetUpdate) AddUserID(v int64) *ImageAssetUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGenerationID sets the "generation_id" field.
func (_u *ImageAssetUpdate) SetGenerationID(v int64) *ImageAssetUpdate {
	_u.mutation.ResetGenerationID()
	_u.mutation.SetGenerationID(v)
	return _u
}

// SetNillableGenerationID sets the "generation_id" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableGenerationID(v *int64) *ImageAssetUpdate {
	if v != nil {
		_u.SetGenerationID(*v)
	}
	return _u
}

// AddGenerationID adds value to the "generation_id" field.
func (_u *ImageAssetUpdate) AddGenerationID(v int64) *ImageAssetUpdate {
	_u.mutation.AddGenerationID(v)
	return _u
}

// SetAssetType sets the "asset_type" field.
func (_u *ImageAssetUpdate) SetAssetType(v imageasset.AssetType) *ImageAssetUpdate {
	_u.mutation.SetAssetType(v)
	return _u
}

// SetNillableAssetType sets the "asset_type" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableAssetType(v *imageasset.AssetType) *ImageAssetUpdate {
	if v != nil {
		_u.SetAssetType(*v)
	}
	return _u
}

// SetS3Bucket sets the "s3_bucket" field.
func (_u *ImageAssetUpdate) SetS3Bucket(v string) *ImageAssetUpdate {
	_u.mutation.SetS3Bucket(v)
	return _u
}

// SetNillableS3Bucket sets the "s3_bucket" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableS3Bucket(v *string) *ImageAssetUpdate {
	if v != nil {
		_u.SetS3Bucket(*v)
	}
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *ImageAssetUpdate) SetS3Key(v string) *ImageAssetUpdate {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableS3Key(v *string) *ImageAssetUpdate {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageAssetUpdate) SetMimeType(v string) *ImageAssetUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableMimeType(v *string) *ImageAssetUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ImageAssetUpdate) SetFileSize(v int64) *ImageAssetUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableFileSize(v *int64) *ImageAssetUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ImageAssetUpdate) AddFileSize(v int64) *ImageAssetUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageAssetUpdate) SetWidth(v int) *ImageAssetUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableWidth(v *int) *ImageAssetUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageAssetUpdate) AddWidth(v int) *ImageAssetUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *ImageAssetUpdate) ClearWidth() *ImageAssetUpdate {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageAssetUpdate) SetHeight(v int) *ImageAssetUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableHeight(v *int) *ImageAssetUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageAssetUpdate) AddHeight(v int) *ImageAssetUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *ImageAssetUpdate) ClearHeight() *ImageAssetUpdate {
	_u.mutation.ClearHeight()
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ImageAssetUpdate) SetSha256(v string) *ImageAssetUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableSha256(v *string) *ImageAssetUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *ImageAssetUpdate) ClearSha256() *ImageAssetUpdate {
	_u.mutation.ClearSha256()
	return _u
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *ImageAssetUpdate) SetOriginalFilename(v string) *ImageAssetUpdate {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *ImageAssetUpdate) SetNillableOriginalFilename(v *string) *ImageAssetUpdate {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (_u *ImageAssetUpdate) ClearOriginalFilename() *ImageAssetUpdate {
	_u.mutation.ClearOriginalFilename()
	return _u
}

// Mutation returns the ImageAssetMutation object of the builder.
func (_u *ImageAssetUpdate) Mutation() *ImageAssetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageAssetUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageAssetUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if imageasset.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageasset.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imageasset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageAssetUpdate) check() error {
	if v, ok := _u.mutation.AssetType(); ok {
		if err := imageasset.AssetTypeValidator(v); err != nil {
			return &ValidationError{Name: "asset_type", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.asset_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.S3Bucket(); ok {
		if err := imageasset.S3BucketValidator(v); err != nil {
			return &ValidationError{Name: "s3_bucket", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.s3_bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.S3Key(); ok {
		if err := imageasset.S3KeyValidator(v); err != nil {
			return &ValidationError{Name: "s3_key", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.s3_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imageasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := imageasset.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalFilename(); ok {
		if err := imageasset.OriginalFilenameValidator(v); err != nil {
			return &ValidationError{Name: "original_filename", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.original_filename": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageasset.Table, imageasset.Columns, sqlgraph.NewFieldSpec(imageasset.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageasset.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(imageasset.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(imageasset.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imageasset.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imageasset.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GenerationID(); ok {
		_spec.SetField(imageasset.FieldGenerationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGenerationID(); ok {
		_spec.AddField(imageasset.FieldGenerationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AssetType(); ok {
		_spec.SetField(imageasset.FieldAssetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.S3Bucket(); ok {
		_spec.SetField(imageasset.FieldS3Bucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(imageasset.FieldS3Key, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imageasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(imageasset.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(imageasset.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imageasset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imageasset.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(imageasset.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imageasset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imageasset.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(imageasset.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(imageasset.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(imageasset.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(imageasset.FieldOriginalFilename, field.TypeString, value)
	}
	if _u.mutation.OriginalFilenameCleared() {
		_spec.ClearField(imageasset.FieldOriginalFilename, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageAssetUpdateOne is the builder for updating a single ImageAsset entity.
type ImageAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageAssetMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageAssetUpdateOne) SetUpdatedAt(v time.Time) *ImageAssetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ImageAssetUpdateOne) SetDeletedAt(v time.Time) *ImageAssetUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableDeletedAt(v *time.Time) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ImageAssetUpdateOne) ClearDeletedAt() *ImageAssetUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageAssetUpdateOne) SetUserID(v int64) *ImageAssetUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableUserID(v *int64) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImageAssetUpdateOne) AddUserID(v int64) *ImageAssetUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGenerationID sets the "generation_id" field.
func (_u *ImageAssetUpdateOne) SetGenerationID(v int64) *ImageAssetUpdateOne {
	_u.mutation.ResetGenerationID()
	_u.mutation.SetGenerationID(v)
	return _u
}

// SetNillableGenerationID sets the "generation_id" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableGenerationID(v *int64) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetGenerationID(*v)
	}
	return _u
}

// AddGenerationID adds value to the "generation_id" field.
func (_u *ImageAssetUpdateOne) AddGenerationID(v int64) *ImageAssetUpdateOne {
	_u.mutation.AddGenerationID(v)
	return _u
}

// SetAssetType sets the "asset_type" field.
func (_u *ImageAssetUpdateOne) SetAssetType(v imageasset.AssetType) *ImageAssetUpdateOne {
	_u.mutation.SetAssetType(v)
	return _u
}

// SetNillableAssetType sets the "asset_type" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableAssetType(v *imageasset.AssetType) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetAssetType(*v)
	}
	return _u
}

// SetS3Bucket sets the "s3_bucket" field.
func (_u *ImageAssetUpdateOne) SetS3Bucket(v string) *ImageAssetUpdateOne {
	_u.mutation.SetS3Bucket(v)
	return _u
}

// SetNillableS3Bucket sets the "s3_bucket" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableS3Bucket(v *string) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetS3Bucket(*v)
	}
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *ImageAssetUpdateOne) SetS3Key(v string) *ImageAssetUpdateOne {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableS3Key(v *string) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageAssetUpdateOne) SetMimeType(v string) *ImageAssetUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableMimeType(v *string) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ImageAssetUpdateOne) SetFileSize(v int64) *ImageAssetUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableFileSize(v *int64) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ImageAssetUpdateOne) AddFileSize(v int64) *ImageAssetUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageAssetUpdateOne) SetWidth(v int) *ImageAssetUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableWidth(v *int) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageAssetUpdateOne) AddWidth(v int) *ImageAssetUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// ClearWidth clears the value of the "width" field.
func (_u *ImageAssetUpdateOne) ClearWidth() *ImageAssetUpdateOne {
	_u.mutation.ClearWidth()
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageAssetUpdateOne) SetHeight(v int) *ImageAssetUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableHeight(v *int) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageAssetUpdateOne) AddHeight(v int) *ImageAssetUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// ClearHeight clears the value of the "height" field.
func (_u *ImageAssetUpdateOne) ClearHeight() *ImageAssetUpdateOne {
	_u.mutation.ClearHeight()
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ImageAssetUpdateOne) SetSha256(v string) *ImageAssetUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableSha256(v *string) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// ClearSha256 clears the value of the "sha256" field.
func (_u *ImageAssetUpdateOne) ClearSha256() *ImageAssetUpdateOne {
	_u.mutation.ClearSha256()
	return _u
}

// SetOriginalFilename sets the "original_filename" field.
func (_u *ImageAssetUpdateOne) SetOriginalFilename(v string) *ImageAssetUpdateOne {
	_u.mutation.SetOriginalFilename(v)
	return _u
}

// SetNillableOriginalFilename sets the "original_filename" field if the given value is not nil.
func (_u *ImageAssetUpdateOne) SetNillableOriginalFilename(v *string) *ImageAssetUpdateOne {
	if v != nil {
		_u.SetOriginalFilename(*v)
	}
	return _u
}

// ClearOriginalFilename clears the value of the "original_filename" field.
func (_u *ImageAssetUpdateOne) ClearOriginalFilename() *ImageAssetUpdateOne {
	_u.mutation.ClearOriginalFilename()
	return _u
}

// Mutation returns the ImageAssetMutation object of the builder.
func (_u *ImageAssetUpdateOne) Mutation() *ImageAssetMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageAssetUpdate builder.
func (_u *ImageAssetUpdateOne) Where(ps ...predicate.ImageAsset) *ImageAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageAssetUpdateOne) Select(field string, fields ...string) *ImageAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageAsset entity.
func (_u *ImageAssetUpdateOne) Save(ctx context.Context) (*ImageAsset, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageAssetUpdateOne) SaveX(ctx context.Context) *ImageAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageAssetUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if imageasset.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageasset.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imageasset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageAssetUpdateOne) check() error {
	if v, ok := _u.mutation.AssetType(); ok {
		if err := imageasset.AssetTypeValidator(v); err != nil {
			return &ValidationError{Name: "asset_type", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.asset_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.S3Bucket(); ok {
		if err := imageasset.S3BucketValidator(v); err != nil {
			return &ValidationError{Name: "s3_bucket", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.s3_bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.S3Key(); ok {
		if err := imageasset.S3KeyValidator(v); err != nil {
			return &ValidationError{Name: "s3_key", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.s3_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imageasset.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := imageasset.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OriginalFilename(); ok {
		if err := imageasset.OriginalFilenameValidator(v); err != nil {
			return &ValidationError{Name: "original_filename", err: fmt.Errorf(`ent: validator failed for field "ImageAsset.original_filename": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageAssetUpdateOne) sqlSave(ctx context.Context) (_node *ImageAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageasset.Table, imageasset.Columns, sqlgraph.NewFieldSpec(imageasset.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imageasset.FieldID)
		for _, f := range fields {
			if !imageasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imageasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageasset.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(imageasset.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(imageasset.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imageasset.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imageasset.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GenerationID(); ok {
		_spec.SetField(imageasset.FieldGenerationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGenerationID(); ok {
		_spec.AddField(imageasset.FieldGenerationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AssetType(); ok {
		_spec.SetField(imageasset.FieldAssetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.S3Bucket(); ok {
		_spec.SetField(imageasset.FieldS3Bucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(imageasset.FieldS3Key, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imageasset.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(imageasset.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(imageasset.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imageasset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imageasset.FieldWidth, field.TypeInt, value)
	}
	if _u.mutation.WidthCleared() {
		_spec.ClearField(imageasset.FieldWidth, field.TypeInt)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imageasset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imageasset.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.HeightCleared() {
		_spec.ClearField(imageasset.FieldHeight, field.TypeInt)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(imageasset.FieldSha256, field.TypeString, value)
	}
	if _u.mutation.Sha256Cleared() {
		_spec.ClearField(imageasset.FieldSha256, field.TypeString)
	}
	if value, ok := _u.mutation.OriginalFilename(); ok {
		_spec.SetField(imageasset.FieldOriginalFilename, field.TypeString, value)
	}
	if _u.mutation.OriginalFilenameCleared() {
		_spec.ClearField(imageasset.FieldOriginalFilename, field.TypeString)
	}
	_node = &ImageAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
