// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagegeneration"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageGenerationUpdate is the builder for updating ImageGeneration entities.
type ImageGenerationUpdate struct {
	config
	hooks    []Hook
	mutation *ImageGenerationMutation
}

// Where appends a list predicates to the ImageGenerationUpdate builder.
func (_u *ImageGenerationUpdate) Where(ps ...predicate.ImageGeneration) *ImageGenerationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageGenerationUpdate) SetUserID(v int64) *ImageGenerationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableUserID(v *int64) *ImageGenerationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImageGenerationUpdate) AddUserID(v int64) *ImageGenerationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ImageGenerationUpdate) SetConversationID(v int64) *ImageGenerationUpdate {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableConversationID(v *int64) *ImageGenerationUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *ImageGenerationUpdate) AddConversationID(v int64) *ImageGenerationUpdate {
	_u.mutation.AddConversationID(v)
	return _u
}

// SetParentGenerationID sets the "parent_generation_id" field.
func (_u *ImageGenerationUpdate) SetParentGenerationID(v int64) *ImageGenerationUpdate {
	_u.mutation.ResetParentGenerationID()
	_u.mutation.SetParentGenerationID(v)
	return _u
}

// SetNillableParentGenerationID sets the "parent_generation_id" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableParentGenerationID(v *int64) *ImageGenerationUpdate {
	if v != nil {
		_u.SetParentGenerationID(*v)
	}
	return _u
}

// AddParentGenerationID adds value to the "parent_generation_id" field.
func (_u *ImageGenerationUpdate) AddParentGenerationID(v int64) *ImageGenerationUpdate {
	_u.mutation.AddParentGenerationID(v)
	return _u
}

// ClearParentGenerationID clears the value of the "parent_generation_id" field.
func (_u *ImageGenerationUpdate) ClearParentGenerationID() *ImageGenerationUpdate {
	_u.mutation.ClearParentGenerationID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ImageGenerationUpdate) SetProvider(v string) *ImageGenerationUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableProvider(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderCredentialID sets the "provider_credential_id" field.
func (_u *ImageGenerationUpdate) SetProviderCredentialID(v int64) *ImageGenerationUpdate {
	_u.mutation.ResetProviderCredentialID()
	_u.mutation.SetProviderCredentialID(v)
	return _u
}

// SetNillableProviderCredentialID sets the "provider_credential_id" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableProviderCredentialID(v *int64) *ImageGenerationUpdate {
	if v != nil {
		_u.SetProviderCredentialID(*v)
	}
	return _u
}

// AddProviderCredentialID adds value to the "provider_credential_id" field.
func (_u *ImageGenerationUpdate) AddProviderCredentialID(v int64) *ImageGenerationUpdate {
	_u.mutation.AddProviderCredentialID(v)
	return _u
}

// ClearProviderCredentialID clears the value of the "provider_credential_id" field.
func (_u *ImageGenerationUpdate) ClearProviderCredentialID() *ImageGenerationUpdate {
	_u.mutation.ClearProviderCredentialID()
	return _u
}

// SetModel sets the "model" field.
func (_u *ImageGenerationUpdate) SetModel(v string) *ImageGenerationUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableModel(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetGenerationType sets the "generation_type" field.
func (_u *ImageGenerationUpdate) SetGenerationType(v imagegeneration.GenerationType) *ImageGenerationUpdate {
	_u.mutation.SetGenerationType(v)
	return _u
}

// SetNillableGenerationType sets the "generation_type" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableGenerationType(v *imagegeneration.GenerationType) *ImageGenerationUpdate {
	if v != nil {
		_u.SetGenerationType(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ImageGenerationUpdate) SetPrompt(v string) *ImageGenerationUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillablePrompt(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *ImageGenerationUpdate) SetSize(v string) *ImageGenerationUpdate {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableSize(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// SetRatio sets the "ratio" field.
func (_u *ImageGenerationUpdate) SetRatio(v string) *ImageGenerationUpdate {
	_u.mutation.SetRatio(v)
	return _u
}

// SetNillableRatio sets the "ratio" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableRatio(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetRatio(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageGenerationUpdate) SetStatus(v imagegeneration.Status) *ImageGenerationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableStatus(v *imagegeneration.Status) *ImageGenerationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ImageGenerationUpdate) SetIdempotencyKey(v string) *ImageGenerationUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableIdempotencyKey(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *ImageGenerationUpdate) ClearIdempotencyKey() *ImageGenerationUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetProviderRequestID sets the "provider_request_id" field.
func (_u *ImageGenerationUpdate) SetProviderRequestID(v string) *ImageGenerationUpdate {
	_u.mutation.SetProviderRequestID(v)
	return _u
}

// SetNillableProviderRequestID sets the "provider_request_id" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableProviderRequestID(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetProviderRequestID(*v)
	}
	return _u
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (_u *ImageGenerationUpdate) ClearProviderRequestID() *ImageGenerationUpdate {
	_u.mutation.ClearProviderRequestID()
	return _u
}

// SetProviderOriginalURL sets the "provider_original_url" field.
func (_u *ImageGenerationUpdate) SetProviderOriginalURL(v string) *ImageGenerationUpdate {
	_u.mutation.SetProviderOriginalURL(v)
	return _u
}

// SetNillableProviderOriginalURL sets the "provider_original_url" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableProviderOriginalURL(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetProviderOriginalURL(*v)
	}
	return _u
}

// ClearProviderOriginalURL clears the value of the "provider_original_url" field.
func (_u *ImageGenerationUpdate) ClearProviderOriginalURL() *ImageGenerationUpdate {
	_u.mutation.ClearProviderOriginalURL()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *ImageGenerationUpdate) SetErrorCode(v string) *ImageGenerationUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableErrorCode(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *ImageGenerationUpdate) ClearErrorCode() *ImageGenerationUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ImageGenerationUpdate) SetErrorMessage(v string) *ImageGenerationUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableErrorMessage(v *string) *ImageGenerationUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ImageGenerationUpdate) ClearErrorMessage() *ImageGenerationUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *ImageGenerationUpdate) SetDurationMs(v int) *ImageGenerationUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableDurationMs(v *int) *ImageGenerationUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *ImageGenerationUpdate) AddDurationMs(v int) *ImageGenerationUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ImageGenerationUpdate) SetStartedAt(v time.Time) *ImageGenerationUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableStartedAt(v *time.Time) *ImageGenerationUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ImageGenerationUpdate) ClearStartedAt() *ImageGenerationUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ImageGenerationUpdate) SetCompletedAt(v time.Time) *ImageGenerationUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ImageGenerationUpdate) SetNillableCompletedAt(v *time.Time) *ImageGenerationUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ImageGenerationUpdate) ClearCompletedAt() *ImageGenerationUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageGenerationUpdate) SetUpdatedAt(v time.Time) *ImageGenerationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ImageGenerationMutation object of the builder.
func (_u *ImageGenerationUpdate) Mutation() *ImageGenerationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageGenerationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageGenerationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageGenerationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageGenerationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageGenerationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagegeneration.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageGenerationUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := imagegeneration.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imagegeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GenerationType(); ok {
		if err := imagegeneration.GenerationTypeValidator(v); err != nil {
			return &ValidationError{Name: "generation_type", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.generation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := imagegeneration.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ratio(); ok {
		if err := imagegeneration.RatioValidator(v); err != nil {
			return &ValidationError{Name: "ratio", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.ratio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imagegeneration.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := imagegeneration.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderRequestID(); ok {
		if err := imagegeneration.ProviderRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_request_id", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOriginalURL(); ok {
		if err := imagegeneration.ProviderOriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "provider_original_url", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider_original_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := imagegeneration.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageGenerationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagegeneration.Table, imagegeneration.Columns, sqlgraph.NewFieldSpec(imagegeneration.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imagegeneration.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imagegeneration.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(imagegeneration.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(imagegeneration.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentGenerationID(); ok {
		_spec.SetField(imagegeneration.FieldParentGenerationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentGenerationID(); ok {
		_spec.AddField(imagegeneration.FieldParentGenerationID, field.TypeInt64, value)
	}
	if _u.mutation.ParentGenerationIDCleared() {
		_spec.ClearField(imagegeneration.FieldParentGenerationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(imagegeneration.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderCredentialID(); ok {
		_spec.SetField(imagegeneration.FieldProviderCredentialID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderCredentialID(); ok {
		_spec.AddField(imagegeneration.FieldProviderCredentialID, field.TypeInt64, value)
	}
	if _u.mutation.ProviderCredentialIDCleared() {
		_spec.ClearField(imagegeneration.FieldProviderCredentialID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imagegeneration.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.GenerationType(); ok {
		_spec.SetField(imagegeneration.FieldGenerationType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(imagegeneration.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(imagegeneration.FieldSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ratio(); ok {
		_spec.SetField(imagegeneration.FieldRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imagegeneration.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(imagegeneration.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(imagegeneration.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderRequestID(); ok {
		_spec.SetField(imagegeneration.FieldProviderRequestID, field.TypeString, value)
	}
	if _u.mutation.ProviderRequestIDCleared() {
		_spec.ClearField(imagegeneration.FieldProviderRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderOriginalURL(); ok {
		_spec.SetField(imagegeneration.FieldProviderOriginalURL, field.TypeString, value)
	}
	if _u.mutation.ProviderOriginalURLCleared() {
		_spec.ClearField(imagegeneration.FieldProviderOriginalURL, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(imagegeneration.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(imagegeneration.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(imagegeneration.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(imagegeneration.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(imagegeneration.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(imagegeneration.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(imagegeneration.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(imagegeneration.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(imagegeneration.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(imagegeneration.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagegeneration.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagegeneration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageGenerationUpdateOne is the builder for updating a single ImageGeneration entity.
type ImageGenerationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageGenerationMutation
}

// SetUserID sets the "user_id" field.
func (_u *ImageGenerationUpdateOne) SetUserID(v int64) *ImageGenerationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableUserID(v *int64) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImageGenerationUpdateOne) AddUserID(v int64) *ImageGenerationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ImageGenerationUpdateOne) SetConversationID(v int64) *ImageGenerationUpdateOne {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableConversationID(v *int64) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *ImageGenerationUpdateOne) AddConversationID(v int64) *ImageGenerationUpdateOne {
	_u.mutation.AddConversationID(v)
	return _u
}

// SetParentGenerationID sets the "parent_generation_id" field.
func (_u *ImageGenerationUpdateOne) SetParentGenerationID(v int64) *ImageGenerationUpdateOne {
	_u.mutation.ResetParentGenerationID()
	_u.mutation.SetParentGenerationID(v)
	return _u
}

// SetNillableParentGenerationID sets the "parent_generation_id" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableParentGenerationID(v *int64) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetParentGenerationID(*v)
	}
	return _u
}

// AddParentGenerationID adds value to the "parent_generation_id" field.
func (_u *ImageGenerationUpdateOne) AddParentGenerationID(v int64) *ImageGenerationUpdateOne {
	_u.mutation.AddParentGenerationID(v)
	return _u
}

// ClearParentGenerationID clears the value of the "parent_generation_id" field.
func (_u *ImageGenerationUpdateOne) ClearParentGenerationID() *ImageGenerationUpdateOne {
	_u.mutation.ClearParentGenerationID()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ImageGenerationUpdateOne) SetProvider(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableProvider(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderCredentialID sets the "provider_credential_id" field.
func (_u *ImageGenerationUpdateOne) SetProviderCredentialID(v int64) *ImageGenerationUpdateOne {
	_u.mutation.ResetProviderCredentialID()
	_u.mutation.SetProviderCredentialID(v)
	return _u
}

// SetNillableProviderCredentialID sets the "provider_credential_id" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableProviderCredentialID(v *int64) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetProviderCredentialID(*v)
	}
	return _u
}

// AddProviderCredentialID adds value to the "provider_credential_id" field.
func (_u *ImageGenerationUpdateOne) AddProviderCredentialID(v int64) *ImageGenerationUpdateOne {
	_u.mutation.AddProviderCredentialID(v)
	return _u
}

// ClearProviderCredentialID clears the value of the "provider_credential_id" field.
func (_u *ImageGenerationUpdateOne) ClearProviderCredentialID() *ImageGenerationUpdateOne {
	_u.mutation.ClearProviderCredentialID()
	return _u
}

// SetModel sets the "model" field.
func (_u *ImageGenerationUpdateOne) SetModel(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableModel(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetGenerationType sets the "generation_type" field.
func (_u *ImageGenerationUpdateOne) SetGenerationType(v imagegeneration.GenerationType) *ImageGenerationUpdateOne {
	_u.mutation.SetGenerationType(v)
	return _u
}

// SetNillableGenerationType sets the "generation_type" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableGenerationType(v *imagegeneration.GenerationType) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetGenerationType(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ImageGenerationUpdateOne) SetPrompt(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillablePrompt(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *ImageGenerationUpdateOne) SetSize(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableSize(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// SetRatio sets the "ratio" field.
func (_u *ImageGenerationUpdateOne) SetRatio(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetRatio(v)
	return _u
}

// SetNillableRatio sets the "ratio" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableRatio(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetRatio(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageGenerationUpdateOne) SetStatus(v imagegeneration.Status) *ImageGenerationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableStatus(v *imagegeneration.Status) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *ImageGenerationUpdateOne) SetIdempotencyKey(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableIdempotencyKey(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *ImageGenerationUpdateOne) ClearIdempotencyKey() *ImageGenerationUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetProviderRequestID sets the "provider_request_id" field.
func (_u *ImageGenerationUpdateOne) SetProviderRequestID(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetProviderRequestID(v)
	return _u
}

// SetNillableProviderRequestID sets the "provider_request_id" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableProviderRequestID(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetProviderRequestID(*v)
	}
	return _u
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (_u *ImageGenerationUpdateOne) ClearProviderRequestID() *ImageGenerationUpdateOne {
	_u.mutation.ClearProviderRequestID()
	return _u
}

// SetProviderOriginalURL sets the "provider_original_url" field.
func (_u *ImageGenerationUpdateOne) SetProviderOriginalURL(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetProviderOriginalURL(v)
	return _u
}

// SetNillableProviderOriginalURL sets the "provider_original_url" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableProviderOriginalURL(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetProviderOriginalURL(*v)
	}
	return _u
}

// ClearProviderOriginalURL clears the value of the "provider_original_url" field.
func (_u *ImageGenerationUpdateOne) ClearProviderOriginalURL() *ImageGenerationUpdateOne {
	_u.mutation.ClearProviderOriginalURL()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *ImageGenerationUpdateOne) SetErrorCode(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableErrorCode(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *ImageGenerationUpdateOne) ClearErrorCode() *ImageGenerationUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ImageGenerationUpdateOne) SetErrorMessage(v string) *ImageGenerationUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableErrorMessage(v *string) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ImageGenerationUpdateOne) ClearErrorMessage() *ImageGenerationUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *ImageGenerationUpdateOne) SetDurationMs(v int) *ImageGenerationUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableDurationMs(v *int) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *ImageGenerationUpdateOne) AddDurationMs(v int) *ImageGenerationUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ImageGenerationUpdateOne) SetStartedAt(v time.Time) *ImageGenerationUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableStartedAt(v *time.Time) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ImageGenerationUpdateOne) ClearStartedAt() *ImageGenerationUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ImageGenerationUpdateOne) SetCompletedAt(v time.Time) *ImageGenerationUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ImageGenerationUpdateOne) SetNillableCompletedAt(v *time.Time) *ImageGenerationUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ImageGenerationUpdateOne) ClearCompletedAt() *ImageGenerationUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageGenerationUpdateOne) SetUpdatedAt(v time.Time) *ImageGenerationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ImageGenerationMutation object of the builder.
func (_u *ImageGenerationUpdateOne) Mutation() *ImageGenerationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageGenerationUpdate builder.
func (_u *ImageGenerationUpdateOne) Where(ps ...predicate.ImageGeneration) *ImageGenerationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageGenerationUpdateOne) Select(field string, fields ...string) *ImageGenerationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageGeneration entity.
func (_u *ImageGenerationUpdateOne) Save(ctx context.Context) (*ImageGeneration, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageGenerationUpdateOne) SaveX(ctx context.Context) *ImageGeneration {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageGenerationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageGenerationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageGenerationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagegeneration.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageGenerationUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := imagegeneration.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imagegeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GenerationType(); ok {
		if err := imagegeneration.GenerationTypeValidator(v); err != nil {
			return &ValidationError{Name: "generation_type", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.generation_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := imagegeneration.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ratio(); ok {
		if err := imagegeneration.RatioValidator(v); err != nil {
			return &ValidationError{Name: "ratio", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.ratio": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imagegeneration.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := imagegeneration.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderRequestID(); ok {
		if err := imagegeneration.ProviderRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_request_id", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOriginalURL(); ok {
		if err := imagegeneration.ProviderOriginalURLValidator(v); err != nil {
			return &ValidationError{Name: "provider_original_url", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.provider_original_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := imagegeneration.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "ImageGeneration.error_code": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageGenerationUpdateOne) sqlSave(ctx context.Context) (_node *ImageGeneration, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagegeneration.Table, imagegeneration.Columns, sqlgraph.NewFieldSpec(imagegeneration.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageGeneration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagegeneration.FieldID)
		for _, f := range fields {
			if !imagegeneration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imagegeneration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imagegeneration.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imagegeneration.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(imagegeneration.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(imagegeneration.FieldConversationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ParentGenerationID(); ok {
		_spec.SetField(imagegeneration.FieldParentGenerationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentGenerationID(); ok {
		_spec.AddField(imagegeneration.FieldParentGenerationID, field.TypeInt64, value)
	}
	if _u.mutation.ParentGenerationIDCleared() {
		_spec.ClearField(imagegeneration.FieldParentGenerationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(imagegeneration.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderCredentialID(); ok {
		_spec.SetField(imagegeneration.FieldProviderCredentialID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderCredentialID(); ok {
		_spec.AddField(imagegeneration.FieldProviderCredentialID, field.TypeInt64, value)
	}
	if _u.mutation.ProviderCredentialIDCleared() {
		_spec.ClearField(imagegeneration.FieldProviderCredentialID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imagegeneration.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.GenerationType(); ok {
		_spec.SetField(imagegeneration.FieldGenerationType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(imagegeneration.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(imagegeneration.FieldSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ratio(); ok {
		_spec.SetField(imagegeneration.FieldRatio, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imagegeneration.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(imagegeneration.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(imagegeneration.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderRequestID(); ok {
		_spec.SetField(imagegeneration.FieldProviderRequestID, field.TypeString, value)
	}
	if _u.mutation.ProviderRequestIDCleared() {
		_spec.ClearField(imagegeneration.FieldProviderRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderOriginalURL(); ok {
		_spec.SetField(imagegeneration.FieldProviderOriginalURL, field.TypeString, value)
	}
	if _u.mutation.ProviderOriginalURLCleared() {
		_spec.ClearField(imagegeneration.FieldProviderOriginalURL, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(imagegeneration.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(imagegeneration.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(imagegeneration.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(imagegeneration.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(imagegeneration.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(imagegeneration.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(imagegeneration.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(imagegeneration.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(imagegeneration.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(imagegeneration.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagegeneration.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ImageGeneration{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagegeneration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
