// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageconversation"
)

// ImageConversationCreate is the builder for creating a ImageConversation entity.
type ImageConversationCreate struct {
	config
	mutation *ImageConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageConversationCreate) SetCreatedAt(v time.Time) *ImageConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageConversationCreate) SetNillableCreatedAt(v *time.Time) *ImageConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImageConversationCreate) SetUpdatedAt(v time.Time) *ImageConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ImageConversationCreate) SetNillableUpdatedAt(v *time.Time) *ImageConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ImageConversationCreate) SetDeletedAt(v time.Time) *ImageConversationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ImageConversationCreate) SetNillableDeletedAt(v *time.Time) *ImageConversationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ImageConversationCreate) SetUserID(v int64) *ImageConversationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ImageConversationCreate) SetTitle(v string) *ImageConversationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ImageConversationCreate) SetNillableTitle(v *string) *ImageConversationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *ImageConversationCreate) SetLastMessageAt(v time.Time) *ImageConversationCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *ImageConversationCreate) SetNillableLastMessageAt(v *time.Time) *ImageConversationCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// Mutation returns the ImageConversationMutation object of the builder.
func (_c *ImageConversationCreate) Mutation() *ImageConversationMutation {
	return _c.mutation
}

// Save creates the ImageConversation in the database.
func (_c *ImageConversationCreate) Save(ctx context.Context) (*ImageConversation, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageConversationCreate) SaveX(ctx context.Context) *ImageConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageConversationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if imageconversation.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageconversation.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := imageconversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if imageconversation.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageconversation.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imageconversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := imageconversation.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageConversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImageConversation.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImageConversation.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ImageConversation.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := imageconversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ImageConversation.title": %w`, err)}
		}
	}
	return nil
}

func (_c *ImageConversationCreate) sqlSave(ctx context.Context) (*ImageConversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageConversationCreate) createSpec() (*ImageConversation, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageConversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imageconversation.Table, sqlgraph.NewFieldSpec(imageconversation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imageconversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imageconversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(imageconversation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(imageconversation.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(imageconversation.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(imageconversation.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageConversation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageConversationCreate) OnConflict(opts ...sql.ConflictOption) *ImageConversationUpsertOne {
	_c.conflict = opts
	return &ImageConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageConversationCreate) OnConflictColumns(columns ...string) *ImageConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageConversationUpsertOne{
		create: _c,
	}
}

type (
	// ImageConversationUpsertOne is the builder for "upsert"-ing
	//  one ImageConversation node.
	ImageConversationUpsertOne struct {
		create *ImageConversationCreate
	}

	// ImageConversationUpsert is the "OnConflict" setter.
	ImageConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageConversationUpsert) SetUpdatedAt(v time.Time) *ImageConversationUpsert {
	u.Set(imageconversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageConversationUpsert) UpdateUpdatedAt() *ImageConversationUpsert {
	u.SetExcluded(imageconversation.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageConversationUpsert) SetDeletedAt(v time.Time) *ImageConversationUpsert {
	u.Set(imageconversation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageConversationUpsert) UpdateDeletedAt() *ImageConversationUpsert {
	u.SetExcluded(imageconversation.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageConversationUpsert) ClearDeletedAt() *ImageConversationUpsert {
	u.SetNull(imageconversation.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImageConversationUpsert) SetUserID(v int64) *ImageConversationUpsert {
	u.Set(imageconversation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageConversationUpsert) UpdateUserID() *ImageConversationUpsert {
	u.SetExcluded(imageconversation.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ImageConversationUpsert) AddUserID(v int64) *ImageConversationUpsert {
	u.Add(imageconversation.FieldUserID, v)
	return u
}

// SetTitle sets the "title" field.
func (u *ImageConversationUpsert) SetTitle(v string) *ImageConversationUpsert {
	u.Set(imageconversation.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImageConversationUpsert) UpdateTitle() *ImageConversationUpsert {
	u.SetExcluded(imageconversation.FieldTitle)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ImageConversationUpsert) SetLastMessageAt(v time.Time) *ImageConversationUpsert {
	u.Set(imageconversation.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ImageConversationUpsert) UpdateLastMessageAt() *ImageConversationUpsert {
	u.SetExcluded(imageconversation.FieldLastMessageAt)
	return u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ImageConversationUpsert) ClearLastMessageAt() *ImageConversationUpsert {
	u.SetNull(imageconversation.FieldLastMessageAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageConversationUpsertOne) UpdateNewValues() *ImageConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imageconversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageConversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageConversationUpsertOne) Ignore() *ImageConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageConversationUpsertOne) DoNothing() *ImageConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageConversationCreate.OnConflict
// documentation for more info.
func (u *ImageConversationUpsertOne) Update(set func(*ImageConversationUpsert)) *ImageConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageConversationUpsertOne) SetUpdatedAt(v time.Time) *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageConversationUpsertOne) UpdateUpdatedAt() *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageConversationUpsertOne) SetDeletedAt(v time.Time) *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageConversationUpsertOne) UpdateDeletedAt() *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageConversationUpsertOne) ClearDeletedAt() *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageConversationUpsertOne) SetUserID(v int64) *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImageConversationUpsertOne) AddUserID(v int64) *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageConversationUpsertOne) UpdateUserID() *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *ImageConversationUpsertOne) SetTitle(v string) *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImageConversationUpsertOne) UpdateTitle() *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateTitle()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ImageConversationUpsertOne) SetLastMessageAt(v time.Time) *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ImageConversationUpsertOne) UpdateLastMessageAt() *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ImageConversationUpsertOne) ClearLastMessageAt() *ImageConversationUpsertOne {
	return u.Update(func(s *ImageConversationUpsert) {
		s.ClearLastMessageAt()
	})
}

// Exec executes the query.
func (u *ImageConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageConversationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageConversationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageConversationCreateBulk is the builder for creating many ImageConversation entities in bulk.
type ImageConversationCreateBulk struct {
	config
	err      error
	builders []*ImageConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageConversation entities in the database.
func (_c *ImageConversationCreateBulk) Save(ctx context.Context) ([]*ImageConversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageConversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageConversationCreateBulk) SaveX(ctx context.Context) []*ImageConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageConversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageConversationUpsertBulk {
	_c.conflict = opts
	return &ImageConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageConversationCreateBulk) OnConflictColumns(columns ...string) *ImageConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageConversationUpsertBulk{
		create: _c,
	}
}

// ImageConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageConversation nodes.
type ImageConversationUpsertBulk struct {
	create *ImageConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageConversationUpsertBulk) UpdateNewValues() *ImageConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imageconversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageConversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageConversationUpsertBulk) Ignore() *ImageConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageConversationUpsertBulk) DoNothing() *ImageConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageConversationCreateBulk.OnConflict
// documentation for more info.
func (u *ImageConversationUpsertBulk) Update(set func(*ImageConversationUpsert)) *ImageConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageConversationUpsertBulk) SetUpdatedAt(v time.Time) *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageConversationUpsertBulk) UpdateUpdatedAt() *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageConversationUpsertBulk) SetDeletedAt(v time.Time) *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageConversationUpsertBulk) UpdateDeletedAt() *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageConversationUpsertBulk) ClearDeletedAt() *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageConversationUpsertBulk) SetUserID(v int64) *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ImageConversationUpsertBulk) AddUserID(v int64) *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageConversationUpsertBulk) UpdateUserID() *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *ImageConversationUpsertBulk) SetTitle(v string) *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImageConversationUpsertBulk) UpdateTitle() *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateTitle()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ImageConversationUpsertBulk) SetLastMessageAt(v time.Time) *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ImageConversationUpsertBulk) UpdateLastMessageAt() *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *ImageConversationUpsertBulk) ClearLastMessageAt() *ImageConversationUpsertBulk {
	return u.Update(func(s *ImageConversationUpsert) {
		s.ClearLastMessageAt()
	})
}

// Exec executes the query.
func (u *ImageConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
