// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageconversation"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageConversationUpdate is the builder for updating ImageConversation entities.
type ImageConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ImageConversationMutation
}

// Where appends a list predicates to the ImageConversationUpdate builder.
func (_u *ImageConversationUpdate) Where(ps ...predicate.ImageConversation) *ImageConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageConversationUpdate) SetUpdatedAt(v time.Time) *ImageConversationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ImageConversationUpdate) SetDeletedAt(v time.Time) *ImageConversationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ImageConversationUpdate) SetNillableDeletedAt(v *time.Time) *ImageConversationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ImageConversationUpdate) ClearDeletedAt() *ImageConversationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageConversationUpdate) SetUserID(v int64) *ImageConversationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageConversationUpdate) SetNillableUserID(v *int64) *ImageConversationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImageConversationUpdate) AddUserID(v int64) *ImageConversationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ImageConversationUpdate) SetTitle(v string) *ImageConversationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ImageConversationUpdate) SetNillableTitle(v *string) *ImageConversationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ImageConversationUpdate) SetLastMessageAt(v time.Time) *ImageConversationUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ImageConversationUpdate) SetNillableLastMessageAt(v *time.Time) *ImageConversationUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *ImageConversationUpdate) ClearLastMessageAt() *ImageConversationUpdate {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// Mutation returns the ImageConversationMutation object of the builder.
func (_u *ImageConversationUpdate) Mutation() *ImageConversationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageConversationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageConversationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if imageconversation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageconversation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imageconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageConversationUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := imageconversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ImageConversation.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageconversation.Table, imageconversation.Columns, sqlgraph.NewFieldSpec(imageconversation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(imageconversation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(imageconversation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imageconversation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imageconversation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(imageconversation.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(imageconversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(imageconversation.FieldLastMessageAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageConversationUpdateOne is the builder for updating a single ImageConversation entity.
type ImageConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageConversationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageConversationUpdateOne) SetUpdatedAt(v time.Time) *ImageConversationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ImageConversationUpdateOne) SetDeletedAt(v time.Time) *ImageConversationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ImageConversationUpdateOne) SetNillableDeletedAt(v *time.Time) *ImageConversationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ImageConversationUpdateOne) ClearDeletedAt() *ImageConversationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageConversationUpdateOne) SetUserID(v int64) *ImageConversationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageConversationUpdateOne) SetNillableUserID(v *int64) *ImageConversationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ImageConversationUpdateOne) AddUserID(v int64) *ImageConversationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ImageConversationUpdateOne) SetTitle(v string) *ImageConversationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ImageConversationUpdateOne) SetNillableTitle(v *string) *ImageConversationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ImageConversationUpdateOne) SetLastMessageAt(v time.Time) *ImageConversationUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ImageConversationUpdateOne) SetNillableLastMessageAt(v *time.Time) *ImageConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *ImageConversationUpdateOne) ClearLastMessageAt() *ImageConversationUpdateOne {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// Mutation returns the ImageConversationMutation object of the builder.
func (_u *ImageConversationUpdateOne) Mutation() *ImageConversationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImageConversationUpdate builder.
func (_u *ImageConversationUpdateOne) Where(ps ...predicate.ImageConversation) *ImageConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageConversationUpdateOne) Select(field string, fields ...string) *ImageConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageConversation entity.
func (_u *ImageConversationUpdateOne) Save(ctx context.Context) (*ImageConversation, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageConversationUpdateOne) SaveX(ctx context.Context) *ImageConversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageConversationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if imageconversation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageconversation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imageconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageConversationUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := imageconversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ImageConversation.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ImageConversationUpdateOne) sqlSave(ctx context.Context) (_node *ImageConversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageconversation.Table, imageconversation.Columns, sqlgraph.NewFieldSpec(imageconversation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageConversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imageconversation.FieldID)
		for _, f := range fields {
			if !imageconversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imageconversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(imageconversation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(imageconversation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(imageconversation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(imageconversation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(imageconversation.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(imageconversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(imageconversation.FieldLastMessageAt, field.TypeTime)
	}
	_node = &ImageConversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
