// Code generated by ent, DO NOT EDIT.

package dailycheckin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldUserID, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldRewardAmount, v))
}

// CheckinDate applies equality check predicate on the "checkin_date" field. It's identical to CheckinDateEQ.
func CheckinDate(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldCheckinDate, v))
}

// CheckinAt applies equality check predicate on the "checkin_at" field. It's identical to CheckinAtEQ.
func CheckinAt(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldCheckinAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNotIn(FieldUserID, vs...))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLTE(FieldRewardAmount, v))
}

// CheckinDateEQ applies the EQ predicate on the "checkin_date" field.
func CheckinDateEQ(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldCheckinDate, v))
}

// CheckinDateNEQ applies the NEQ predicate on the "checkin_date" field.
func CheckinDateNEQ(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNEQ(FieldCheckinDate, v))
}

// CheckinDateIn applies the In predicate on the "checkin_date" field.
func CheckinDateIn(vs ...string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldIn(FieldCheckinDate, vs...))
}

// CheckinDateNotIn applies the NotIn predicate on the "checkin_date" field.
func CheckinDateNotIn(vs ...string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNotIn(FieldCheckinDate, vs...))
}

// CheckinDateGT applies the GT predicate on the "checkin_date" field.
func CheckinDateGT(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGT(FieldCheckinDate, v))
}

// CheckinDateGTE applies the GTE predicate on the "checkin_date" field.
func CheckinDateGTE(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGTE(FieldCheckinDate, v))
}

// CheckinDateLT applies the LT predicate on the "checkin_date" field.
func CheckinDateLT(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLT(FieldCheckinDate, v))
}

// CheckinDateLTE applies the LTE predicate on the "checkin_date" field.
func CheckinDateLTE(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLTE(FieldCheckinDate, v))
}

// CheckinDateContains applies the Contains predicate on the "checkin_date" field.
func CheckinDateContains(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldContains(FieldCheckinDate, v))
}

// CheckinDateHasPrefix applies the HasPrefix predicate on the "checkin_date" field.
func CheckinDateHasPrefix(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldHasPrefix(FieldCheckinDate, v))
}

// CheckinDateHasSuffix applies the HasSuffix predicate on the "checkin_date" field.
func CheckinDateHasSuffix(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldHasSuffix(FieldCheckinDate, v))
}

// CheckinDateEqualFold applies the EqualFold predicate on the "checkin_date" field.
func CheckinDateEqualFold(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEqualFold(FieldCheckinDate, v))
}

// CheckinDateContainsFold applies the ContainsFold predicate on the "checkin_date" field.
func CheckinDateContainsFold(v string) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldContainsFold(FieldCheckinDate, v))
}

// CheckinAtEQ applies the EQ predicate on the "checkin_at" field.
func CheckinAtEQ(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldEQ(FieldCheckinAt, v))
}

// CheckinAtNEQ applies the NEQ predicate on the "checkin_at" field.
func CheckinAtNEQ(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNEQ(FieldCheckinAt, v))
}

// CheckinAtIn applies the In predicate on the "checkin_at" field.
func CheckinAtIn(vs ...time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldIn(FieldCheckinAt, vs...))
}

// CheckinAtNotIn applies the NotIn predicate on the "checkin_at" field.
func CheckinAtNotIn(vs ...time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldNotIn(FieldCheckinAt, vs...))
}

// CheckinAtGT applies the GT predicate on the "checkin_at" field.
func CheckinAtGT(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGT(FieldCheckinAt, v))
}

// CheckinAtGTE applies the GTE predicate on the "checkin_at" field.
func CheckinAtGTE(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldGTE(FieldCheckinAt, v))
}

// CheckinAtLT applies the LT predicate on the "checkin_at" field.
func CheckinAtLT(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLT(FieldCheckinAt, v))
}

// CheckinAtLTE applies the LTE predicate on the "checkin_at" field.
func CheckinAtLTE(v time.Time) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.FieldLTE(FieldCheckinAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DailyCheckin {
	return predicate.DailyCheckin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.DailyCheckin {
	return predicate.DailyCheckin(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DailyCheckin) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DailyCheckin) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DailyCheckin) predicate.DailyCheckin {
	return predicate.DailyCheckin(sql.NotPredicates(p))
}
