// Code generated by ent, DO NOT EDIT.

package imagegeneration

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the imagegeneration type in the database.
	Label = "image_generation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// FieldParentGenerationID holds the string denoting the parent_generation_id field in the database.
	FieldParentGenerationID = "parent_generation_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderCredentialID holds the string denoting the provider_credential_id field in the database.
	FieldProviderCredentialID = "provider_credential_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldGenerationType holds the string denoting the generation_type field in the database.
	FieldGenerationType = "generation_type"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldRatio holds the string denoting the ratio field in the database.
	FieldRatio = "ratio"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldProviderRequestID holds the string denoting the provider_request_id field in the database.
	FieldProviderRequestID = "provider_request_id"
	// FieldProviderOriginalURL holds the string denoting the provider_original_url field in the database.
	FieldProviderOriginalURL = "provider_original_url"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the imagegeneration in the database.
	Table = "image_generations"
)

// Columns holds all SQL columns for imagegeneration fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldConversationID,
	FieldParentGenerationID,
	FieldProvider,
	FieldProviderCredentialID,
	FieldModel,
	FieldGenerationType,
	FieldPrompt,
	FieldSize,
	FieldRatio,
	FieldStatus,
	FieldIdempotencyKey,
	FieldProviderRequestID,
	FieldProviderOriginalURL,
	FieldErrorCode,
	FieldErrorMessage,
	FieldDurationMs,
	FieldStartedAt,
	FieldCompletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize string
	// SizeValidator is a validator for the "size" field. It is called by the builders before save.
	SizeValidator func(string) error
	// DefaultRatio holds the default value on creation for the "ratio" field.
	DefaultRatio string
	// RatioValidator is a validator for the "ratio" field. It is called by the builders before save.
	RatioValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// ProviderRequestIDValidator is a validator for the "provider_request_id" field. It is called by the builders before save.
	ProviderRequestIDValidator func(string) error
	// ProviderOriginalURLValidator is a validator for the "provider_original_url" field. It is called by the builders before save.
	ProviderOriginalURLValidator func(string) error
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// GenerationType defines the type for the "generation_type" enum field.
type GenerationType string

// GenerationType values.
const (
	GenerationTypeTextToImage  GenerationType = "text_to_image"
	GenerationTypeImageToImage GenerationType = "image_to_image"
)

func (gt GenerationType) String() string {
	return string(gt)
}

// GenerationTypeValidator is a validator for the "generation_type" field enum values. It is called by the builders before save.
func GenerationTypeValidator(gt GenerationType) error {
	switch gt {
	case GenerationTypeTextToImage, GenerationTypeImageToImage:
		return nil
	default:
		return fmt.Errorf("imagegeneration: invalid enum value for generation_type field: %q", gt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending    Status = "pending"
	StatusQueued     Status = "queued"
	StatusProcessing Status = "processing"
	StatusSucceeded  Status = "succeeded"
	StatusFailed     Status = "failed"
	StatusCanceled   Status = "canceled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusQueued, StatusProcessing, StatusSucceeded, StatusFailed, StatusCanceled:
		return nil
	default:
		return fmt.Errorf("imagegeneration: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ImageGeneration queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByParentGenerationID orders the results by the parent_generation_id field.
func ByParentGenerationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentGenerationID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderCredentialID orders the results by the provider_credential_id field.
func ByProviderCredentialID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderCredentialID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByGenerationType orders the results by the generation_type field.
func ByGenerationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenerationType, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByRatio orders the results by the ratio field.
func ByRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRatio, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByProviderRequestID orders the results by the provider_request_id field.
func ByProviderRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRequestID, opts...).ToFunc()
}

// ByProviderOriginalURL orders the results by the provider_original_url field.
func ByProviderOriginalURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderOriginalURL, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
