// Code generated by ent, DO NOT EDIT.

package imagegeneration

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldUserID, v))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldConversationID, v))
}

// ParentGenerationID applies equality check predicate on the "parent_generation_id" field. It's identical to ParentGenerationIDEQ.
func ParentGenerationID(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldParentGenerationID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldProvider, v))
}

// ProviderCredentialID applies equality check predicate on the "provider_credential_id" field. It's identical to ProviderCredentialIDEQ.
func ProviderCredentialID(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldProviderCredentialID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldModel, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldPrompt, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldSize, v))
}

// Ratio applies equality check predicate on the "ratio" field. It's identical to RatioEQ.
func Ratio(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldRatio, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldIdempotencyKey, v))
}

// ProviderRequestID applies equality check predicate on the "provider_request_id" field. It's identical to ProviderRequestIDEQ.
func ProviderRequestID(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldProviderRequestID, v))
}

// ProviderOriginalURL applies equality check predicate on the "provider_original_url" field. It's identical to ProviderOriginalURLEQ.
func ProviderOriginalURL(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldProviderOriginalURL, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldErrorMessage, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldDurationMs, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldCompletedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldUserID, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldConversationID, v))
}

// ParentGenerationIDEQ applies the EQ predicate on the "parent_generation_id" field.
func ParentGenerationIDEQ(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldParentGenerationID, v))
}

// ParentGenerationIDNEQ applies the NEQ predicate on the "parent_generation_id" field.
func ParentGenerationIDNEQ(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldParentGenerationID, v))
}

// ParentGenerationIDIn applies the In predicate on the "parent_generation_id" field.
func ParentGenerationIDIn(vs ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldParentGenerationID, vs...))
}

// ParentGenerationIDNotIn applies the NotIn predicate on the "parent_generation_id" field.
func ParentGenerationIDNotIn(vs ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldParentGenerationID, vs...))
}

// ParentGenerationIDGT applies the GT predicate on the "parent_generation_id" field.
func ParentGenerationIDGT(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldParentGenerationID, v))
}

// ParentGenerationIDGTE applies the GTE predicate on the "parent_generation_id" field.
func ParentGenerationIDGTE(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldParentGenerationID, v))
}

// ParentGenerationIDLT applies the LT predicate on the "parent_generation_id" field.
func ParentGenerationIDLT(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldParentGenerationID, v))
}

// ParentGenerationIDLTE applies the LTE predicate on the "parent_generation_id" field.
func ParentGenerationIDLTE(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldParentGenerationID, v))
}

// ParentGenerationIDIsNil applies the IsNil predicate on the "parent_generation_id" field.
func ParentGenerationIDIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldParentGenerationID))
}

// ParentGenerationIDNotNil applies the NotNil predicate on the "parent_generation_id" field.
func ParentGenerationIDNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldParentGenerationID))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderCredentialIDEQ applies the EQ predicate on the "provider_credential_id" field.
func ProviderCredentialIDEQ(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldProviderCredentialID, v))
}

// ProviderCredentialIDNEQ applies the NEQ predicate on the "provider_credential_id" field.
func ProviderCredentialIDNEQ(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldProviderCredentialID, v))
}

// ProviderCredentialIDIn applies the In predicate on the "provider_credential_id" field.
func ProviderCredentialIDIn(vs ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldProviderCredentialID, vs...))
}

// ProviderCredentialIDNotIn applies the NotIn predicate on the "provider_credential_id" field.
func ProviderCredentialIDNotIn(vs ...int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldProviderCredentialID, vs...))
}

// ProviderCredentialIDGT applies the GT predicate on the "provider_credential_id" field.
func ProviderCredentialIDGT(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldProviderCredentialID, v))
}

// ProviderCredentialIDGTE applies the GTE predicate on the "provider_credential_id" field.
func ProviderCredentialIDGTE(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldProviderCredentialID, v))
}

// ProviderCredentialIDLT applies the LT predicate on the "provider_credential_id" field.
func ProviderCredentialIDLT(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldProviderCredentialID, v))
}

// ProviderCredentialIDLTE applies the LTE predicate on the "provider_credential_id" field.
func ProviderCredentialIDLTE(v int64) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldProviderCredentialID, v))
}

// ProviderCredentialIDIsNil applies the IsNil predicate on the "provider_credential_id" field.
func ProviderCredentialIDIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldProviderCredentialID))
}

// ProviderCredentialIDNotNil applies the NotNil predicate on the "provider_credential_id" field.
func ProviderCredentialIDNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldProviderCredentialID))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldModel, v))
}

// GenerationTypeEQ applies the EQ predicate on the "generation_type" field.
func GenerationTypeEQ(v GenerationType) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldGenerationType, v))
}

// GenerationTypeNEQ applies the NEQ predicate on the "generation_type" field.
func GenerationTypeNEQ(v GenerationType) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldGenerationType, v))
}

// GenerationTypeIn applies the In predicate on the "generation_type" field.
func GenerationTypeIn(vs ...GenerationType) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldGenerationType, vs...))
}

// GenerationTypeNotIn applies the NotIn predicate on the "generation_type" field.
func GenerationTypeNotIn(vs ...GenerationType) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldGenerationType, vs...))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldPrompt, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldSize, v))
}

// SizeContains applies the Contains predicate on the "size" field.
func SizeContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldSize, v))
}

// SizeHasPrefix applies the HasPrefix predicate on the "size" field.
func SizeHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldSize, v))
}

// SizeHasSuffix applies the HasSuffix predicate on the "size" field.
func SizeHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldSize, v))
}

// SizeEqualFold applies the EqualFold predicate on the "size" field.
func SizeEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldSize, v))
}

// SizeContainsFold applies the ContainsFold predicate on the "size" field.
func SizeContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldSize, v))
}

// RatioEQ applies the EQ predicate on the "ratio" field.
func RatioEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldRatio, v))
}

// RatioNEQ applies the NEQ predicate on the "ratio" field.
func RatioNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldRatio, v))
}

// RatioIn applies the In predicate on the "ratio" field.
func RatioIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldRatio, vs...))
}

// RatioNotIn applies the NotIn predicate on the "ratio" field.
func RatioNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldRatio, vs...))
}

// RatioGT applies the GT predicate on the "ratio" field.
func RatioGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldRatio, v))
}

// RatioGTE applies the GTE predicate on the "ratio" field.
func RatioGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldRatio, v))
}

// RatioLT applies the LT predicate on the "ratio" field.
func RatioLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldRatio, v))
}

// RatioLTE applies the LTE predicate on the "ratio" field.
func RatioLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldRatio, v))
}

// RatioContains applies the Contains predicate on the "ratio" field.
func RatioContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldRatio, v))
}

// RatioHasPrefix applies the HasPrefix predicate on the "ratio" field.
func RatioHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldRatio, v))
}

// RatioHasSuffix applies the HasSuffix predicate on the "ratio" field.
func RatioHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldRatio, v))
}

// RatioEqualFold applies the EqualFold predicate on the "ratio" field.
func RatioEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldRatio, v))
}

// RatioContainsFold applies the ContainsFold predicate on the "ratio" field.
func RatioContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldRatio, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldStatus, vs...))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// ProviderRequestIDEQ applies the EQ predicate on the "provider_request_id" field.
func ProviderRequestIDEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldProviderRequestID, v))
}

// ProviderRequestIDNEQ applies the NEQ predicate on the "provider_request_id" field.
func ProviderRequestIDNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldProviderRequestID, v))
}

// ProviderRequestIDIn applies the In predicate on the "provider_request_id" field.
func ProviderRequestIDIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldProviderRequestID, vs...))
}

// ProviderRequestIDNotIn applies the NotIn predicate on the "provider_request_id" field.
func ProviderRequestIDNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldProviderRequestID, vs...))
}

// ProviderRequestIDGT applies the GT predicate on the "provider_request_id" field.
func ProviderRequestIDGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldProviderRequestID, v))
}

// ProviderRequestIDGTE applies the GTE predicate on the "provider_request_id" field.
func ProviderRequestIDGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldProviderRequestID, v))
}

// ProviderRequestIDLT applies the LT predicate on the "provider_request_id" field.
func ProviderRequestIDLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldProviderRequestID, v))
}

// ProviderRequestIDLTE applies the LTE predicate on the "provider_request_id" field.
func ProviderRequestIDLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldProviderRequestID, v))
}

// ProviderRequestIDContains applies the Contains predicate on the "provider_request_id" field.
func ProviderRequestIDContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldProviderRequestID, v))
}

// ProviderRequestIDHasPrefix applies the HasPrefix predicate on the "provider_request_id" field.
func ProviderRequestIDHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldProviderRequestID, v))
}

// ProviderRequestIDHasSuffix applies the HasSuffix predicate on the "provider_request_id" field.
func ProviderRequestIDHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldProviderRequestID, v))
}

// ProviderRequestIDIsNil applies the IsNil predicate on the "provider_request_id" field.
func ProviderRequestIDIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldProviderRequestID))
}

// ProviderRequestIDNotNil applies the NotNil predicate on the "provider_request_id" field.
func ProviderRequestIDNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldProviderRequestID))
}

// ProviderRequestIDEqualFold applies the EqualFold predicate on the "provider_request_id" field.
func ProviderRequestIDEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldProviderRequestID, v))
}

// ProviderRequestIDContainsFold applies the ContainsFold predicate on the "provider_request_id" field.
func ProviderRequestIDContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldProviderRequestID, v))
}

// ProviderOriginalURLEQ applies the EQ predicate on the "provider_original_url" field.
func ProviderOriginalURLEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLNEQ applies the NEQ predicate on the "provider_original_url" field.
func ProviderOriginalURLNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLIn applies the In predicate on the "provider_original_url" field.
func ProviderOriginalURLIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldProviderOriginalURL, vs...))
}

// ProviderOriginalURLNotIn applies the NotIn predicate on the "provider_original_url" field.
func ProviderOriginalURLNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldProviderOriginalURL, vs...))
}

// ProviderOriginalURLGT applies the GT predicate on the "provider_original_url" field.
func ProviderOriginalURLGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLGTE applies the GTE predicate on the "provider_original_url" field.
func ProviderOriginalURLGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLLT applies the LT predicate on the "provider_original_url" field.
func ProviderOriginalURLLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLLTE applies the LTE predicate on the "provider_original_url" field.
func ProviderOriginalURLLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLContains applies the Contains predicate on the "provider_original_url" field.
func ProviderOriginalURLContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLHasPrefix applies the HasPrefix predicate on the "provider_original_url" field.
func ProviderOriginalURLHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLHasSuffix applies the HasSuffix predicate on the "provider_original_url" field.
func ProviderOriginalURLHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLIsNil applies the IsNil predicate on the "provider_original_url" field.
func ProviderOriginalURLIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldProviderOriginalURL))
}

// ProviderOriginalURLNotNil applies the NotNil predicate on the "provider_original_url" field.
func ProviderOriginalURLNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldProviderOriginalURL))
}

// ProviderOriginalURLEqualFold applies the EqualFold predicate on the "provider_original_url" field.
func ProviderOriginalURLEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldProviderOriginalURL, v))
}

// ProviderOriginalURLContainsFold applies the ContainsFold predicate on the "provider_original_url" field.
func ProviderOriginalURLContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldProviderOriginalURL, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldContainsFold(FieldErrorMessage, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldDurationMs, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotNull(FieldCompletedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageGeneration) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageGeneration) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageGeneration) predicate.ImageGeneration {
	return predicate.ImageGeneration(sql.NotPredicates(p))
}
