// Code generated by ent, DO NOT EDIT.

package imageprovidercredential

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the imageprovidercredential type in the database.
	Label = "image_provider_credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldAPIKeyEncrypted holds the string denoting the api_key_encrypted field in the database.
	FieldAPIKeyEncrypted = "api_key_encrypted"
	// FieldKeyFingerprint holds the string denoting the key_fingerprint field in the database.
	FieldKeyFingerprint = "key_fingerprint"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldConsecutiveFailures holds the string denoting the consecutive_failures field in the database.
	FieldConsecutiveFailures = "consecutive_failures"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// FieldLastFailureAt holds the string denoting the last_failure_at field in the database.
	FieldLastFailureAt = "last_failure_at"
	// FieldCooldownUntil holds the string denoting the cooldown_until field in the database.
	FieldCooldownUntil = "cooldown_until"
	// FieldLastErrorCode holds the string denoting the last_error_code field in the database.
	FieldLastErrorCode = "last_error_code"
	// FieldLastErrorMessage holds the string denoting the last_error_message field in the database.
	FieldLastErrorMessage = "last_error_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the imageprovidercredential in the database.
	Table = "image_provider_credentials"
)

// Columns holds all SQL columns for imageprovidercredential fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldProvider,
	FieldAPIKeyEncrypted,
	FieldKeyFingerprint,
	FieldEnabled,
	FieldPriority,
	FieldWeight,
	FieldStatus,
	FieldConsecutiveFailures,
	FieldLastUsedAt,
	FieldLastSuccessAt,
	FieldLastFailureAt,
	FieldCooldownUntil,
	FieldLastErrorCode,
	FieldLastErrorMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// APIKeyEncryptedValidator is a validator for the "api_key_encrypted" field. It is called by the builders before save.
	APIKeyEncryptedValidator func(string) error
	// KeyFingerprintValidator is a validator for the "key_fingerprint" field. It is called by the builders before save.
	KeyFingerprintValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	WeightValidator func(int) error
	// DefaultConsecutiveFailures holds the default value on creation for the "consecutive_failures" field.
	DefaultConsecutiveFailures int
	// LastErrorCodeValidator is a validator for the "last_error_code" field. It is called by the builders before save.
	LastErrorCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Provider defines the type for the "provider" enum field.
type Provider string

// Provider values.
const (
	ProviderAgnes Provider = "agnes"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderAgnes:
		return nil
	default:
		return fmt.Errorf("imageprovidercredential: invalid enum value for provider field: %q", pr)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusHealthy is the default value of the Status enum.
const DefaultStatus = StatusHealthy

// Status values.
const (
	StatusHealthy   Status = "healthy"
	StatusUnhealthy Status = "unhealthy"
	StatusDisabled  Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusHealthy, StatusUnhealthy, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("imageprovidercredential: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ImageProviderCredential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByAPIKeyEncrypted orders the results by the api_key_encrypted field.
func ByAPIKeyEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyEncrypted, opts...).ToFunc()
}

// ByKeyFingerprint orders the results by the key_fingerprint field.
func ByKeyFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyFingerprint, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByConsecutiveFailures orders the results by the consecutive_failures field.
func ByConsecutiveFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveFailures, opts...).ToFunc()
}

// ByLastUsedAt orders the results by the last_used_at field.
func ByLastUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsedAt, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}

// ByLastFailureAt orders the results by the last_failure_at field.
func ByLastFailureAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastFailureAt, opts...).ToFunc()
}

// ByCooldownUntil orders the results by the cooldown_until field.
func ByCooldownUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownUntil, opts...).ToFunc()
}

// ByLastErrorCode orders the results by the last_error_code field.
func ByLastErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorCode, opts...).ToFunc()
}

// ByLastErrorMessage orders the results by the last_error_message field.
func ByLastErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
