// Code generated by ent, DO NOT EDIT.

package imageprovidercredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldName, v))
}

// APIKeyEncrypted applies equality check predicate on the "api_key_encrypted" field. It's identical to APIKeyEncryptedEQ.
func APIKeyEncrypted(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldAPIKeyEncrypted, v))
}

// KeyFingerprint applies equality check predicate on the "key_fingerprint" field. It's identical to KeyFingerprintEQ.
func KeyFingerprint(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldKeyFingerprint, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldEnabled, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldPriority, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldWeight, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastSuccessAt applies equality check predicate on the "last_success_at" field. It's identical to LastSuccessAtEQ.
func LastSuccessAt(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastFailureAt applies equality check predicate on the "last_failure_at" field. It's identical to LastFailureAtEQ.
func LastFailureAt(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastFailureAt, v))
}

// CooldownUntil applies equality check predicate on the "cooldown_until" field. It's identical to CooldownUntilEQ.
func CooldownUntil(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldCooldownUntil, v))
}

// LastErrorCode applies equality check predicate on the "last_error_code" field. It's identical to LastErrorCodeEQ.
func LastErrorCode(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorMessage applies equality check predicate on the "last_error_message" field. It's identical to LastErrorMessageEQ.
func LastErrorMessage(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContainsFold(FieldName, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldProvider, vs...))
}

// APIKeyEncryptedEQ applies the EQ predicate on the "api_key_encrypted" field.
func APIKeyEncryptedEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedNEQ applies the NEQ predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedIn applies the In predicate on the "api_key_encrypted" field.
func APIKeyEncryptedIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldAPIKeyEncrypted, vs...))
}

// APIKeyEncryptedNotIn applies the NotIn predicate on the "api_key_encrypted" field.
func APIKeyEncryptedNotIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldAPIKeyEncrypted, vs...))
}

// APIKeyEncryptedGT applies the GT predicate on the "api_key_encrypted" field.
func APIKeyEncryptedGT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedGTE applies the GTE predicate on the "api_key_encrypted" field.
func APIKeyEncryptedGTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedLT applies the LT predicate on the "api_key_encrypted" field.
func APIKeyEncryptedLT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedLTE applies the LTE predicate on the "api_key_encrypted" field.
func APIKeyEncryptedLTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedContains applies the Contains predicate on the "api_key_encrypted" field.
func APIKeyEncryptedContains(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContains(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedHasPrefix applies the HasPrefix predicate on the "api_key_encrypted" field.
func APIKeyEncryptedHasPrefix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasPrefix(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedHasSuffix applies the HasSuffix predicate on the "api_key_encrypted" field.
func APIKeyEncryptedHasSuffix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasSuffix(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedEqualFold applies the EqualFold predicate on the "api_key_encrypted" field.
func APIKeyEncryptedEqualFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEqualFold(FieldAPIKeyEncrypted, v))
}

// APIKeyEncryptedContainsFold applies the ContainsFold predicate on the "api_key_encrypted" field.
func APIKeyEncryptedContainsFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContainsFold(FieldAPIKeyEncrypted, v))
}

// KeyFingerprintEQ applies the EQ predicate on the "key_fingerprint" field.
func KeyFingerprintEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldKeyFingerprint, v))
}

// KeyFingerprintNEQ applies the NEQ predicate on the "key_fingerprint" field.
func KeyFingerprintNEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldKeyFingerprint, v))
}

// KeyFingerprintIn applies the In predicate on the "key_fingerprint" field.
func KeyFingerprintIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldKeyFingerprint, vs...))
}

// KeyFingerprintNotIn applies the NotIn predicate on the "key_fingerprint" field.
func KeyFingerprintNotIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldKeyFingerprint, vs...))
}

// KeyFingerprintGT applies the GT predicate on the "key_fingerprint" field.
func KeyFingerprintGT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldKeyFingerprint, v))
}

// KeyFingerprintGTE applies the GTE predicate on the "key_fingerprint" field.
func KeyFingerprintGTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldKeyFingerprint, v))
}

// KeyFingerprintLT applies the LT predicate on the "key_fingerprint" field.
func KeyFingerprintLT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldKeyFingerprint, v))
}

// KeyFingerprintLTE applies the LTE predicate on the "key_fingerprint" field.
func KeyFingerprintLTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldKeyFingerprint, v))
}

// KeyFingerprintContains applies the Contains predicate on the "key_fingerprint" field.
func KeyFingerprintContains(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContains(FieldKeyFingerprint, v))
}

// KeyFingerprintHasPrefix applies the HasPrefix predicate on the "key_fingerprint" field.
func KeyFingerprintHasPrefix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasPrefix(FieldKeyFingerprint, v))
}

// KeyFingerprintHasSuffix applies the HasSuffix predicate on the "key_fingerprint" field.
func KeyFingerprintHasSuffix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasSuffix(FieldKeyFingerprint, v))
}

// KeyFingerprintEqualFold applies the EqualFold predicate on the "key_fingerprint" field.
func KeyFingerprintEqualFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEqualFold(FieldKeyFingerprint, v))
}

// KeyFingerprintContainsFold applies the ContainsFold predicate on the "key_fingerprint" field.
func KeyFingerprintContainsFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContainsFold(FieldKeyFingerprint, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldEnabled, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldPriority, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldWeight, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldStatus, vs...))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotNull(FieldLastUsedAt))
}

// LastSuccessAtEQ applies the EQ predicate on the "last_success_at" field.
func LastSuccessAtEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtNEQ applies the NEQ predicate on the "last_success_at" field.
func LastSuccessAtNEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtIn applies the In predicate on the "last_success_at" field.
func LastSuccessAtIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtNotIn applies the NotIn predicate on the "last_success_at" field.
func LastSuccessAtNotIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtGT applies the GT predicate on the "last_success_at" field.
func LastSuccessAtGT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldLastSuccessAt, v))
}

// LastSuccessAtGTE applies the GTE predicate on the "last_success_at" field.
func LastSuccessAtGTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldLastSuccessAt, v))
}

// LastSuccessAtLT applies the LT predicate on the "last_success_at" field.
func LastSuccessAtLT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldLastSuccessAt, v))
}

// LastSuccessAtLTE applies the LTE predicate on the "last_success_at" field.
func LastSuccessAtLTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldLastSuccessAt, v))
}

// LastSuccessAtIsNil applies the IsNil predicate on the "last_success_at" field.
func LastSuccessAtIsNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIsNull(FieldLastSuccessAt))
}

// LastSuccessAtNotNil applies the NotNil predicate on the "last_success_at" field.
func LastSuccessAtNotNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotNull(FieldLastSuccessAt))
}

// LastFailureAtEQ applies the EQ predicate on the "last_failure_at" field.
func LastFailureAtEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastFailureAt, v))
}

// LastFailureAtNEQ applies the NEQ predicate on the "last_failure_at" field.
func LastFailureAtNEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldLastFailureAt, v))
}

// LastFailureAtIn applies the In predicate on the "last_failure_at" field.
func LastFailureAtIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldLastFailureAt, vs...))
}

// LastFailureAtNotIn applies the NotIn predicate on the "last_failure_at" field.
func LastFailureAtNotIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldLastFailureAt, vs...))
}

// LastFailureAtGT applies the GT predicate on the "last_failure_at" field.
func LastFailureAtGT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldLastFailureAt, v))
}

// LastFailureAtGTE applies the GTE predicate on the "last_failure_at" field.
func LastFailureAtGTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldLastFailureAt, v))
}

// LastFailureAtLT applies the LT predicate on the "last_failure_at" field.
func LastFailureAtLT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldLastFailureAt, v))
}

// LastFailureAtLTE applies the LTE predicate on the "last_failure_at" field.
func LastFailureAtLTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldLastFailureAt, v))
}

// LastFailureAtIsNil applies the IsNil predicate on the "last_failure_at" field.
func LastFailureAtIsNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIsNull(FieldLastFailureAt))
}

// LastFailureAtNotNil applies the NotNil predicate on the "last_failure_at" field.
func LastFailureAtNotNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotNull(FieldLastFailureAt))
}

// CooldownUntilEQ applies the EQ predicate on the "cooldown_until" field.
func CooldownUntilEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldCooldownUntil, v))
}

// CooldownUntilNEQ applies the NEQ predicate on the "cooldown_until" field.
func CooldownUntilNEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldCooldownUntil, v))
}

// CooldownUntilIn applies the In predicate on the "cooldown_until" field.
func CooldownUntilIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldCooldownUntil, vs...))
}

// CooldownUntilNotIn applies the NotIn predicate on the "cooldown_until" field.
func CooldownUntilNotIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldCooldownUntil, vs...))
}

// CooldownUntilGT applies the GT predicate on the "cooldown_until" field.
func CooldownUntilGT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldCooldownUntil, v))
}

// CooldownUntilGTE applies the GTE predicate on the "cooldown_until" field.
func CooldownUntilGTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldCooldownUntil, v))
}

// CooldownUntilLT applies the LT predicate on the "cooldown_until" field.
func CooldownUntilLT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldCooldownUntil, v))
}

// CooldownUntilLTE applies the LTE predicate on the "cooldown_until" field.
func CooldownUntilLTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldCooldownUntil, v))
}

// CooldownUntilIsNil applies the IsNil predicate on the "cooldown_until" field.
func CooldownUntilIsNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIsNull(FieldCooldownUntil))
}

// CooldownUntilNotNil applies the NotNil predicate on the "cooldown_until" field.
func CooldownUntilNotNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotNull(FieldCooldownUntil))
}

// LastErrorCodeEQ applies the EQ predicate on the "last_error_code" field.
func LastErrorCodeEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastErrorCode, v))
}

// LastErrorCodeNEQ applies the NEQ predicate on the "last_error_code" field.
func LastErrorCodeNEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldLastErrorCode, v))
}

// LastErrorCodeIn applies the In predicate on the "last_error_code" field.
func LastErrorCodeIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeNotIn applies the NotIn predicate on the "last_error_code" field.
func LastErrorCodeNotIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldLastErrorCode, vs...))
}

// LastErrorCodeGT applies the GT predicate on the "last_error_code" field.
func LastErrorCodeGT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldLastErrorCode, v))
}

// LastErrorCodeGTE applies the GTE predicate on the "last_error_code" field.
func LastErrorCodeGTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldLastErrorCode, v))
}

// LastErrorCodeLT applies the LT predicate on the "last_error_code" field.
func LastErrorCodeLT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldLastErrorCode, v))
}

// LastErrorCodeLTE applies the LTE predicate on the "last_error_code" field.
func LastErrorCodeLTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldLastErrorCode, v))
}

// LastErrorCodeContains applies the Contains predicate on the "last_error_code" field.
func LastErrorCodeContains(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContains(FieldLastErrorCode, v))
}

// LastErrorCodeHasPrefix applies the HasPrefix predicate on the "last_error_code" field.
func LastErrorCodeHasPrefix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasPrefix(FieldLastErrorCode, v))
}

// LastErrorCodeHasSuffix applies the HasSuffix predicate on the "last_error_code" field.
func LastErrorCodeHasSuffix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasSuffix(FieldLastErrorCode, v))
}

// LastErrorCodeIsNil applies the IsNil predicate on the "last_error_code" field.
func LastErrorCodeIsNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIsNull(FieldLastErrorCode))
}

// LastErrorCodeNotNil applies the NotNil predicate on the "last_error_code" field.
func LastErrorCodeNotNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotNull(FieldLastErrorCode))
}

// LastErrorCodeEqualFold applies the EqualFold predicate on the "last_error_code" field.
func LastErrorCodeEqualFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEqualFold(FieldLastErrorCode, v))
}

// LastErrorCodeContainsFold applies the ContainsFold predicate on the "last_error_code" field.
func LastErrorCodeContainsFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContainsFold(FieldLastErrorCode, v))
}

// LastErrorMessageEQ applies the EQ predicate on the "last_error_message" field.
func LastErrorMessageEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageNEQ applies the NEQ predicate on the "last_error_message" field.
func LastErrorMessageNEQ(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldLastErrorMessage, v))
}

// LastErrorMessageIn applies the In predicate on the "last_error_message" field.
func LastErrorMessageIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageNotIn applies the NotIn predicate on the "last_error_message" field.
func LastErrorMessageNotIn(vs ...string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldLastErrorMessage, vs...))
}

// LastErrorMessageGT applies the GT predicate on the "last_error_message" field.
func LastErrorMessageGT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldLastErrorMessage, v))
}

// LastErrorMessageGTE applies the GTE predicate on the "last_error_message" field.
func LastErrorMessageGTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldLastErrorMessage, v))
}

// LastErrorMessageLT applies the LT predicate on the "last_error_message" field.
func LastErrorMessageLT(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldLastErrorMessage, v))
}

// LastErrorMessageLTE applies the LTE predicate on the "last_error_message" field.
func LastErrorMessageLTE(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldLastErrorMessage, v))
}

// LastErrorMessageContains applies the Contains predicate on the "last_error_message" field.
func LastErrorMessageContains(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContains(FieldLastErrorMessage, v))
}

// LastErrorMessageHasPrefix applies the HasPrefix predicate on the "last_error_message" field.
func LastErrorMessageHasPrefix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasPrefix(FieldLastErrorMessage, v))
}

// LastErrorMessageHasSuffix applies the HasSuffix predicate on the "last_error_message" field.
func LastErrorMessageHasSuffix(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldHasSuffix(FieldLastErrorMessage, v))
}

// LastErrorMessageIsNil applies the IsNil predicate on the "last_error_message" field.
func LastErrorMessageIsNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIsNull(FieldLastErrorMessage))
}

// LastErrorMessageNotNil applies the NotNil predicate on the "last_error_message" field.
func LastErrorMessageNotNil() predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotNull(FieldLastErrorMessage))
}

// LastErrorMessageEqualFold applies the EqualFold predicate on the "last_error_message" field.
func LastErrorMessageEqualFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEqualFold(FieldLastErrorMessage, v))
}

// LastErrorMessageContainsFold applies the ContainsFold predicate on the "last_error_message" field.
func LastErrorMessageContainsFold(v string) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldContainsFold(FieldLastErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageProviderCredential) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageProviderCredential) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageProviderCredential) predicate.ImageProviderCredential {
	return predicate.ImageProviderCredential(sql.NotPredicates(p))
}
